-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_gameofthrone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_gameofthrone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_gameofthrone` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_gameofthrone` ;

-- -----------------------------------------------------
-- Table `db_gameofthrone`.`casas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gameofthrone`.`casas` (
  `House_name` TEXT NOT NULL,
  `Region` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `db_gameofthrone`.`episodios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gameofthrone`.`episodios` (
  `Season` INT NOT NULL,
  `Episode` INT NOT NULL,
  `Title` TEXT NOT NULL,
  `Release_date` TEXT NOT NULL,
  `Rating` FLOAT NOT NULL,
  `Votes` INT NOT NULL,
  `Summary` TEXT NOT NULL,
  `Writer_1` TEXT NOT NULL,
  `Writer_2` TEXT NOT NULL,
  `Star_1` TEXT NOT NULL,
  `Star_2` TEXT NOT NULL,
  `Star_3` TEXT NOT NULL,
  `Users_reviews` INT NOT NULL,
  `Critics_reviews` INT NOT NULL,
  `US_Viewers` DECIMAL NOT NULL,
  `Duration` INT NOT NULL,
  `Director` TEXT NOT NULL,
  PRIMARY KEY (`Episode`, `Season`),
  INDEX `fk_episodios_episodios1_idx` (`Season` ASC) VISIBLE,
  CONSTRAINT `fk_episodios_episodios1`
    FOREIGN KEY (`Season`)
    REFERENCES `db_gameofthrone`.`episodios` (`Episode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_gameofthrone`.`personagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gameofthrone`.`personagens` (
  `Character_id` INT NOT NULL,
  `Character` TEXT NOT NULL,
  `Actor/ess` TEXT NOT NULL,
  `Episodes_appeared` INT NOT NULL,
  `First_appearance` INT NOT NULL,
  `Last_appearance` INT NOT NULL,
  PRIMARY KEY (`Character_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO casas (House_name, Region) VALUES
	('Algood', 'Westerlands'),
	('Allyrion of Godsgrace', 'Dorne'),
	('Amber', 'North'),
	('Ambrose', 'Reach'),
	('Andrik of Southshield', 'Iron Islands (Shield Islands)'),
	('Appleton of Appleton', 'Reach'),
	('Arryn of Gulltown', 'Vale of Arryn'),
	('Arryn of the Eyrie', 'Vale of Arryn'),
	('Ashford of Ashford', 'Reach'),
	('Ashwood', 'North'),
	('Baelish of Harrenhal', 'Riverlands'),
	('Baelish of the Fingers', 'Vale of Arryn'),
	('Ball', 'Reach'),
	('Banefort of Banefort', 'Westerlands'),
	('Bar Emmon of Sharp Point', 'Crownlands (Dragonstone)'),
	('Baratheon of Dragonstone', 'Crownlands (Dragonstone)'),
	('Baratheon of King\'s Landing', 'Crownlands'),
	('Baratheon of Storm\'s End', 'Stormlands'),
	('Beesbury of Honeyholt', 'Reach'),
	('Belgrave', 'Unknown'),
	('Belmore of Strongsong', 'Vale of Arryn'),
	('Bettley', 'Westerlands'),
	('Bigglestone', 'Riverlands'),
	('Blackbar of Bandallon', 'Reach'),
	('Blackberry', 'Unknown'),
	('Blackfyre', 'Crownlands'),
	('Blackmont of Blackmont', 'Dorne'),
	('Blackmyre', 'North (Crannogmen)'),
	('Blacktyde of Blacktyde', 'Iron Islands'),
	('Blackwood of Raventree Hall', 'Riverlands; North (formerly)'),
	('Blanetree', 'Riverlands'),
	('Blount', 'Crownlands'),
	('Boggs', 'Crownlands (Crackclaw Point)'),
	('Boggs', 'North (Crannogmen)'),
	('Bole', 'North (Wolfswood Clans)'),
	('Bolling', 'Stormlands'),
	('Bolton of the Dreadfort', 'North'),
	('Bolton of Winterfell', 'North'),
	('Borrell of Sweetsister', 'Vale of Arryn (Sistermen)'),
	('Botley of Lordsport', 'Iron Islands'),
	('Bracken of Stone Hedge', 'Riverlands'),
	('Branch', 'North (Wolfswood Clans)'),
	('Brax of Hornvale', 'Westerlands'),
	('Breakstone', 'Vale of Arryn'),
	('Briar', 'Dorne'),
	('Bridges', 'Reach'),
	('Brightstone', 'Vale of Arryn'),
	('Brook', 'Dorne'),
	('Broom', 'Westerlands'),
	('Brownhill', 'Dorne'),
	('Brune of Brownhollow', 'Crownlands (Crackclaw Point)'),
	('Brune of the Dyre Den', 'Crownlands (Crackclaw Point)'),
	('Buckler of Bronzegate', 'Stormlands'),
	('Buckwell of the Antlers', 'Crownlands'),
	('Bulwer of Blackcrown', 'Reach'),
	('Burley', 'North (Mountain Clans)'),
	('Bushy', 'Reach'),
	('Butterwell of Whitewalls', 'Riverlands'),
	('Byrch', 'Crownlands'),
	('Bywater', 'Crownlands'),
	('Cafferen of Fawnton', 'Stormlands'),
	('Cargyll', 'Crownlands'),
	('Caron of Nightsong', 'Stormlands (Marcher Lords)'),
	('Cassel', 'North'),
	('Casterly of Casterly Rock', 'Westerlands'),
	('Caswell of Bitterbridge', 'Reach'),
	('Cave', 'Crownlands (Crackclaw Point)'),
	('Celtigar of Claw Isle', 'Crownlands (Dragonstone)'),
	('Cerwyn of Castle Cerwyn', 'North'),
	('Chambers', 'Riverlands'),
	('Charlton', 'Riverlands'),
	('Chelsted', 'Crownlands'),
	('Chester of Greenshield', 'Reach (Shield Islands)'),
	('Chyttering', 'Crownlands'),
	('Clegane of Clegane\'s Keep', 'Westerlands'),
	('Clifton', 'Westerlands'),
	('Cobb', 'Reach'),
	('Cockshaw', 'Reach'),
	('Codd', 'Iron Islands'),
	('Coldwater of Coldwater Burn', 'Vale of Arryn'),
	('Cole', 'Stormlands'),
	('Condon', 'North'),
	('Conklyn', 'Reach'),
	('Connington of Griffin\'s Roost', 'Stormlands'),
	('Corbray of Heart\'s Home', 'Vale of Arryn'),
	('Cordwayner of Hammerhal', 'Reach'),
	('Costayne of the Three Towers', 'Reach'),
	('Cox of Saltpans', 'Riverlands'),
	('Crabb of the Whispers', 'Crownlands (Crackclaw Point)'),
	('Crakehall of Crakehall', 'Westerlands'),
	('Crane of Red Lake', 'Reach'),
	('Cray', 'North (Crannogmen)'),
	('Cressey', 'Crownlands'),
	('Crowl of Deepdown', 'North (Skagosi Clans)'),
	('Cupps', 'Unknown'),
	('Cuy of Sunhouse', 'Reach'),
	('Dalt of Lemonwood', 'Dorne'),
	('Dargood', 'Crownlands'),
	('Darke', 'Crownlands'),
	('Darklyn of Duskendale', 'Crownlands'),
	('Darkwood', 'Crownlands'),
	('Darry of Darry', 'Riverlands'),
	('Dayne of High Hermitage', 'Dorne'),
	('Dayne of Starfall', 'Dorne'),
	('Deddings', 'Riverlands'),
	('Doggett', 'Westerlands'),
	('Dondarrion of Blackhaven', 'Stormlands (Marcher Lords)'),
	('Donniger', 'Vale of Arryn'),
	('Drinkwater', 'Dorne'),
	('Drox', 'Westerlands'),
	('Drumm of Old Wyk', 'Iron Islands'),
	('Dryland of Hellgate Hall', 'Dorne'),
	('Dunn', 'Reach'),
	('Durrandon', 'Stormlands'),
	('Durwell', 'Reach'),
	('Dustin of Barrowton', 'North'),
	('Edgerton', 'Crownlands'),
	('Egen', 'Vale of Arryn'),
	('Elesham of the Paps', 'Vale of Arryn'),
	('Erenford', 'Riverlands'),
	('Errol of Haystack Hall', 'Stormlands'),
	('Estermont of Greenstone', 'Stormlands'),
	('Estren of Wyndhall', 'Westerlands'),
	('Falwell', 'Westerlands'),
	('Farman of Faircastle', 'Westerlands'),
	('Farring', 'Crownlands'),
	('Farrow', 'Unknown'),
	('Farwynd of Sealskin Point', 'Iron Islands'),
	('Farwynd of the Lonely Light', 'Iron Islands'),
	('Fell of Felwood', 'Stormlands'),
	('Fenn', 'North (Crannogmen)'),
	('Ferren', 'Westerlands'),
	('Fisher of the Misty Isle', 'Riverlands'),
	('Fisher of the Stony Shore', 'North'),
	('Flint of Breakstone Hill', 'North'),
	('Flint of Flint\'s Finger', 'North'),
	('Flint of the mountains', 'North (Mountain Clans)'),
	('Flint of Widow\'s Watch', 'North'),
	('Florent of Brightwater Keep', 'Reach'),
	('Follard', 'Crownlands'),
	('Foote', 'Westerlands'),
	('Foote of Nightsong', 'Stormlands (Marcher Lords)'),
	('Footly of Tumbleton', 'Reach'),
	('Forrester', 'North (Wolfswood Clans)'),
	('Fossoway of Cider Hall', 'Reach'),
	('Fossoway of New Barrel', 'Reach'),
	('Fowler of Skyreach', 'Dorne'),
	('Frey of Riverrun', 'Riverlands'),
	('Frey of the Crossing', 'Riverlands'),
	('Frost', 'North'),
	('Gardener of Highgarden', 'Reach'),
	('Gargalen of Salt Shore', 'Dorne'),
	('Garner', 'Westerlands'),
	('Gaunt', 'Crownlands'),
	('Glover of Deepwood Motte', 'North'),
	('Goodbrook', 'Riverlands'),
	('Goodbrother of Corpse Lake', 'Iron Islands'),
	('Goodbrother of Crow Spike Keep', 'Iron Islands'),
	('Goodbrother of Downdelving', 'Iron Islands'),
	('Goodbrother of Orkmont', 'Iron Islands'),
	('Goodbrother of Shatterstone', 'Iron Islands'),
	('Goodbrother of Hammerhorn', 'Iron Islands'),
	('Goode', 'Unknown'),
	('Gower', 'Stormlands'),
	('Graceford of Holyhall', 'Reach'),
	('Grafton of Gulltown', 'Vale of Arryn'),
	('Grandison of Grandview', 'Stormlands'),
	('Graves', 'Reach'),
	('Greenfield of Greenfield', 'Westerlands'),
	('Greengood', 'North (Crannogmen)'),
	('Greenhill', 'Unknown'),
	('Greenwood', 'North'),
	('Grell', 'Riverlands'),
	('Grey', 'Riverlands'),
	('Greyiron of Orkmont', 'Iron Islands'),
	('Greyjoy of Pyke', 'Iron Islands'),
	('Greystark of the Wolf\'s Den', 'North'),
	('Grimm of Greyshield', 'Reach (Shield Islands)'),
	('Groves', 'Unknown'),
	('Haigh', 'Riverlands'),
	('Hamell', 'Westerlands'),
	('Harclay', 'North (Mountain Clans)'),
	('Hardy', 'Crownlands (Crackclaw Point)'),
	('Hardyng', 'Vale of Arryn'),
	('Harlaw of Grey Garden', 'Iron Islands (Shield Islands)'),
	('Harlaw of Harlaw Hall', 'Iron Islands'),
	('Harlaw of Harridan Hill', 'Iron Islands'),
	('Harlaw of Harlaw', 'Iron Islands'),
	('Harlaw of the Tower of Glimmering', 'Iron Islands'),
	('Harroway of Harrenhal', 'Riverlands'),
	('Harte', 'Crownlands'),
	('Hastwyck', 'Reach'),
	('Hasty', 'Stormlands'),
	('Hawick of Saltpans', 'Riverlands'),
	('Hawthorne', 'Westerlands'),
	('Hayford of Hayford', 'Crownlands'),
	('Heddle', 'Riverlands'),
	('Herston', 'Stormlands'),
	('Hersy of Newkeep', 'Vale of Arryn'),
	('Hetherspoon', 'Westerlands'),
	('Hewett of Oakenshield', 'Reach (Shield Islands)'),
	('Hightower of the Hightower', 'Reach'),
	('Hoare of Orkmont', 'Iron Islands (origin); Riverlands'),
	('Hogg of Sow\'s Horn', 'Crownlands'),
	('Hollard', 'Crownlands'),
	('Holt', 'North'),
	('Holt', 'Dorne'),
	('Hook', 'Riverlands'),
	('Hornwood of Hornwood', 'North'),
	('Horpe', 'Stormlands'),
	('Hull', 'Dorne'),
	('Humble', 'Iron Islands'),
	('Hunt', 'Reach'),
	('Hunter of Longbow Hall', 'Vale of Arryn'),
	('Hutcheson', 'Reach'),
	('Inchfield', 'Reach'),
	('Ironmaker', 'Iron Islands'),
	('Ironsmith', 'North'),
	('Jast', 'Westerlands'),
	('Jordayne of the Tor', 'Dorne'),
	('Justman', 'Riverlands'),
	('Karstark of Karhold', 'North'),
	('Keath', 'Riverlands'),
	('Kellington', 'Stormlands'),
	('Kenning of Harlaw', 'Iron Islands'),
	('Kenning of Kayce', 'Westerlands'),
	('Kettleblack', 'Crownlands'),
	('Kidwell of Ivy Hall', 'Reach'),
	('Knott', 'North (Mountain Clans)'),
	('Kyndall', 'Westerlands'),
	('Ladybright', 'Dorne'),
	('Lake', 'Dorne'),
	('Lake', 'North'),
	('Langward', 'Crownlands'),
	('Lannett', 'Westerlands'),
	('Lannister of Casterly Rock', 'Westerlands'),
	('Lannister of Darry', 'Riverlands'),
	('Lannister of Lannisport', 'Westerlands'),
	('Lanny', 'Westerlands'),
	('Lantell', 'Westerlands'),
	('Leek', 'Unknown'),
	('Lefford of the Golden Tooth', 'Westerlands'),
	('Leygood', 'Reach'),
	('Liddle', 'North (Mountain Clans)'),
	('Lightfoot', 'North'),
	('Lipps', 'Vale of Arryn'),
	('Locke of Oldcastle', 'North'),
	('Lolliston', 'Riverlands'),
	('Long', 'North'),
	('Longthorpe of Longsister', 'Vale of Arryn (Sistermen)'),
	('Longwaters', 'Crownlands'),
	('Lonmouth', 'Stormlands'),
	('Lorch', 'Westerlands'),
	('Lothston of Harrenhal', 'Riverlands'),
	('Lowther', 'Reach'),
	('Lyberr', 'Reach'),
	('Lychester', 'Riverlands'),
	('Lydden of Deep Den', 'Westerlands'),
	('Lynderly of Snakewood', 'Vale of Arryn'),
	('Magnar of Kingshouse', 'North (Skagosi Clans)'),
	('Mallery', 'Crownlands'),
	('Mallister of Seagard', 'Riverlands'),
	('Manderly of White Harbor', 'North; Reach (formerly)'),
	('Mandrake', 'Unknown'),
	('Manning', 'Crownlands'),
	('Manwoody of Kingsgrave', 'Dorne'),
	('Marbrand of Ashemark', 'Westerlands'),
	('Marsh', 'North'),
	('Martell of Sunspear', 'Dorne'),
	('Massey of Stonedance', 'Crownlands'),
	('Meadows of Grassy Vale', 'Reach'),
	('Melcolm of Old Anchor', 'Vale of Arryn'),
	('Merlyn of Pebbleton', 'Iron Islands'),
	('Merryweather of Longtable', 'Reach'),
	('Mertyns of Mistwood', 'Stormlands'),
	('Middlebury', 'Reach'),
	('Mollen', 'North'),
	('Moore', 'Vale of Arryn'),
	('Mooton of Maidenpool', 'Riverlands'),
	('Moreland', 'Westerlands'),
	('Mormont of Bear Island', 'North'),
	('Morrigen of Crow\'s Nest', 'Stormlands'),
	('Moss', 'North'),
	('Mudd of Oldstones', 'Riverlands'),
	('Mullendore of Uplands', 'Reach'),
	('Musgood', 'Stormlands'),
	('Myatt', 'Westerlands'),
	('Myre of Harlaw', 'Iron Islands'),
	('Nayland of Hag\'s Mire', 'Riverlands'),
	('Netley', 'Iron Islands'),
	('Norcross', 'Reach'),
	('Norrey', 'North (Mountain Clans)'),
	('Norridge', 'Reach'),
	('Nute of Oakenshield', 'Iron Islands (Shield Islands)'),
	('Nutt', 'Riverlands'),
	('Oakheart of Old Oak', 'Reach'),
	('Oldflowers', 'Reach'),
	('Orkwood of Orkmont', 'Iron Islands'),
	('Orme', 'Reach'),
	('Osgrey of Leafy Lake', 'Reach'),
	('Osgrey of Standfast', 'Reach'),
	('Overton', 'North'),
	('Paege', 'Riverlands'),
	('Parren', 'Westerlands'),
	('Payne', 'Westerlands'),
	('Peake of Starpike', 'Reach'),
	('Peasebury of Poddingfield', 'Stormlands'),
	('Peat', 'North (Crannogmen)'),
	('Peckledon', 'Westerlands'),
	('Pemford', 'Riverlands'),
	('Penny', 'Unknown'),
	('Penrose of Parchments', 'Stormlands'),
	('Perryn', 'Riverlands'),
	('Piper of Pinkmaiden', 'Riverlands'),
	('Plumm', 'Westerlands'),
	('Pommingham', 'Reach'),
	('Poole', 'North'),
	('Potter', 'Unknown'),
	('Prester of Feastfires', 'Westerlands'),
	('Pryor of Pebble', 'Vale of Arryn'),
	('Pyle', 'Crownlands'),
	('Pyne', 'Crownlands (Crackclaw Point)'),
	('Qoherys of Harrenhal', 'Riverlands'),
	('Qorgyle of Sandstone', 'Dorne'),
	('Quagg', 'North (Crannogmen)'),
	('Rambton', 'Crownlands'),
	('Redbeard', 'North'),
	('Redding', 'Reach'),
	('Redfort of Redfort', 'Vale of Arryn'),
	('Redwyne of the Arbor', 'Reach'),
	('Reed of Greywater Watch', 'North (Crannogmen)'),
	('Reyne of Castamere', 'Westerlands'),
	('Rhysling', 'Reach'),
	('Risley of Risley Glade', 'Reach'),
	('Rogers of Amberly', 'Stormlands'),
	('Rollingford', 'Crownlands'),
	('Roote of Lord Harroway\'s Town', 'Riverlands'),
	('Rosby of Rosby', 'Crownlands'),
	('Rowan of Goldengrove', 'Reach'),
	('Roxton of the Ring', 'Reach'),
	('Royce of Runestone', 'Vale of Arryn'),
	('Royce of the Gates of the Moon', 'Vale of Arryn'),
	('Ruskyn', 'Unknown'),
	('Ruthermont', 'Vale of Arryn'),
	('Ruttiger', 'Westerlands'),
	('Ryder of the Rills', 'North'),
	('Ryger of Willow Wood', 'Riverlands'),
	('Rykker of Duskendale', 'Crownlands'),
	('Ryswell of the Rills', 'North'),
	('Saltcliffe of Saltcliffe', 'Iron Islands'),
	('Santagar of Spottswood', 'Dorne'),
	('Sarsfield of Sarsfield', 'Westerlands'),
	('Sawyer', 'Unknown'),
	('Seaworth of Cape Wrath', 'Stormlands'),
	('Selmy of Harvest Hall', 'Stormlands (Marcher Lords)'),
	('Serrett of Silverhill', 'Westerlands'),
	('Serry of Southshield', 'Reach (Shield Islands)'),
	('Sharp', 'Iron Islands'),
	('Shawney', 'Riverlands'),
	('Shell', 'Vale of Arryn'),
	('Shell', 'Dorne'),
	('Shepherd', 'Iron Islands'),
	('Shermer of Smithyton', 'Reach'),
	('Shett of Gull Tower', 'Vale of Arryn'),
	('Shett of Gulltown', 'Vale of Arryn'),
	('Slate of Blackpool', 'North'),
	('Sloane', 'Reach'),
	('Slynt of Harrenhal', 'Crownlands (origin); Riverlands (deposed)'),
	('Smallwood of Acorn Hall', 'Riverlands'),
	('Sparr of Great Wyk', 'Iron Islands'),
	('Spicer of Castamere', 'Westerlands'),
	('Stackhouse', 'Reach'),
	('Stackspear', 'Westerlands'),
	('Staedmon of Broad Arch', 'Stormlands'),
	('Stane of Driftwood Hall', 'North (Skagosi Clans)'),
	('Stark of Winterfell', 'North'),
	('Staunton of Rook\'s Rest', 'Crownlands'),
	('Stokeworth of Stokeworth', 'Crownlands'),
	('Stonehouse of Old Wyk', 'Iron Islands'),
	('Stonetree of Harlaw', 'Iron Islands'),
	('Stout of Goldgrass', 'North'),
	('Strickland', 'Unknown'),
	('Strong of Harrenhal', 'Riverlands'),
	('Suggs', 'Unknown'),
	('Sunderland of the Three Sisters', 'Vale of Arryn (Sistermen)'),
	('Sunderly of Saltcliffe', 'Iron Islands'),
	('Sunglass of Sweetport Sound', 'Crownlands (Dragonstone)'),
	('Swann of Stonehelm', 'Stormlands (Marcher Lords)'),
	('Swyft of Cornfield', 'Westerlands'),
	('Swygert', 'Stormlands'),
	('Tallhart of Torrhen\'s Square', 'North'),
	('Tarbeck of Tarbeck Hall', 'Westerlands'),
	('Targaryen of King\'s Landing', 'Crownlands'),
	('Tarly of Horn Hill', 'Reach'),
	('Tarth of Evenfall Hall', 'Stormlands'),
	('Tawney of Orkmont', 'Iron Islands'),
	('Teague', 'Riverlands'),
	('Templeton of Ninestars', 'Vale of Arryn'),
	('Terrick', 'Riverlands'),
	('Thenn', 'North'),
	('Thorne', 'Crownlands'),
	('Toland of Ghost Hill', 'Dorne'),
	('Tollett of the Grey Glen', 'Vale of Arryn'),
	('Torrent of Littlesister', 'Vale of Arryn (Sistermen)'),
	('Towers', 'North'),
	('Towers of Harrenhal', 'Riverlands'),
	('Toyne', 'Stormlands'),
	('Trant of Gallowsgrey', 'Stormlands'),
	('Tudbury', 'Stormlands'),
	('Tully of Riverrun', 'Riverlands'),
	('Turnberry', 'Westerlands'),
	('Tyrell of Brightwater Keep', 'Reach'),
	('Tyrell of Highgarden', 'Reach'),
	('Uffering', 'Reach'),
	('Uller of the Hellholt', 'Dorne'),
	('Umber of the Last Hearth', 'North'),
	('Upcliff of the Witch Isle', 'Vale of Arryn'),
	('Vaith of the Red Dunes', 'Dorne'),
	('Vance of Atranta', 'Riverlands'),
	('Vance of Wayfarer\'s Rest', 'Riverlands'),
	('Varner', 'Reach'),
	('Velaryon of Driftmark', 'Crownlands (Dragonstone)'),
	('Vikary', 'Westerlands'),
	('Volmark of Volmark', 'Iron Islands (Shield Islands)'),
	('Vypren', 'Riverlands'),
	('Vyrwel of Darkdell', 'Reach'),
	('Wade', 'Dorne'),
	('Wagstaff', 'Stormlands'),
	('Warrick', 'Unknown'),
	('Waterman', 'North'),
	('Waxley of Wickenden', 'Vale of Arryn'),
	('Wayn', 'Riverlands'),
	('Waynwood of Ironoaks', 'Vale of Arryn'),
	('Weatherwax', 'Unknown'),
	('Weaver', 'Iron Islands'),
	('Webber of Coldmoat', 'Reach'),
	('Wells', 'Dorne'),
	('Wells', 'North'),
	('Wendwater', 'Crownlands'),
	('Wensington', 'Stormlands'),
	('Westbrook', 'Reach'),
	('Westerling of the Crag', 'Westerlands'),
	('Whitfield', 'Unknown'),
	('Whent of Harrenhal', 'Riverlands'),
	('Whitehead of the Weeping Town', 'Stormlands'),
	('Whitehill of Highpoint', 'North'),
	('Willum', 'Reach'),
	('Wode', 'Riverlands'),
	('Woodfoot of Bear Island', 'North'),
	('Woodhull', 'Vale of Arryn'),
	('Woods', 'North (Wolfswood Clans)'),
	('Woodwright', 'Reach'),
	('Woolfield', 'North'),
	('Wull', 'North (Mountain Clans)'),
	('Wydman', 'Vale of Arryn'),
	('Wyl of the Boneway', 'Dorne'),
	('Wylde of Rain House', 'Stormlands'),
	('Wynch of Iron Holt', 'Iron Islands'),
	('Wythers', 'Reach'),
	('Yarwyck', 'Westerlands'),
	('Yelshire', 'Reach'),
	('Yew', 'Westerlands'),
	('Yronwood of Yronwood', 'Dorne'),
	('Branfield', 'Unknown'),
	('Forrester of Ironrath', 'North (Wolfswood Clans)'),
	('Glenmore of Rillwater Crossing', 'North'),
	('Tuttle', 'North'),
	('Whitehill', 'North'),
	('Harlton of Castlewood', 'Riverlands'),
	('Sarwyck of Riverspring', 'Westerlands'),
	('Westford', 'Westerlands');


INSERT INTO casas (Season, Episode, Title, Release_date, Rating, Votes, Summary, Writer_1, Writer_2, Star_1, Star_2, Star_3, Users_reviews, Critics_reviews, US_Viewers, Duration, Director, Budget_estimate) VALUES
	('1', '1', 'Winter Is Coming', '17-Apr-11', '9.1', '38639', 'Eddard Stark is torn between his family and an old friend when asked to serve at the side of King Robert Baratheon; Viserys plans to wed his sister to a nomadic warlord in exchange for an army.', 'David Benioff', 'D.B. Weiss', 'Sean Bean', 'Mark Addy', 'Nikolaj Coster-Waldau', '61', '30', '2.22', '62', 'Timothy Van Patten', '0'),
	('1', '2', 'The Kingsroad', '24-Apr-11', '8.8', '29285', '"While Bran recovers from his fall, Ned takes only his daughters to King\'s Landing. Jon Snow goes with his uncle Benjen to the Wall. Tyrion joins them."', 'David Benioff', 'D.B. Weiss', 'Sean Bean', 'Mark Addy', 'Nikolaj Coster-Waldau', '27', '28', '2.2', '56', 'Timothy Van Patten', '0'),
	('1', '3', 'Lord Snow', '1-May-11', '8.7', '27694', 'Jon begins his training with the Night\'s Watch; Ned confronts his past and future at King\'s Landing; Daenerys finds herself at odds with Viserys.', 'David Benioff', 'D.B. Weiss', 'Sean Bean', 'Mark Addy', 'Nikolaj Coster-Waldau', '21', '29', '2.44', '58', 'Brian Kirk', '0'),
	('1', '4', '"Cripples, Bastards, and Broken Things"', '8-May-11', '8.8', '26284', '"Eddard investigates Jon Arryn\'s murder. Jon befriends Samwell Tarly, a coward who has come to join the Night\'s Watch."', 'David Benioff', 'D.B. Weiss', 'Sean Bean', 'Mark Addy', 'Nikolaj Coster-Waldau', '22', '26', '2.45', '56', 'Brian Kirk', '0'),
	('1', '5', 'The Wolf and the Lion', '15-May-11', '9.1', '27349', '"Catelyn has captured Tyrion and plans to bring him to her sister, Lysa Arryn, at the Vale, to be tried for his, supposed, crimes against Bran. Robert plans to have Daenerys killed, but Eddard refuses to be a part of it and quits."', 'David Benioff', 'D.B. Weiss', 'Sean Bean', 'Mark Addy', 'Nikolaj Coster-Waldau', '24', '26', '2.58', '55', 'Brian Kirk', '0'),
	('1', '6', 'A Golden Crown', '22-May-11', '9.2', '27079', '"While recovering from his battle with Jaime, Eddard is forced to run the kingdom while Robert goes hunting. Tyrion demands a trial by combat for his freedom. Viserys is losing his patience with Drogo."', 'David Benioff', 'D.B. Weiss', 'Sean Bean', 'Mark Addy', 'Michelle Fairley', '23', '26', '2.44', '53', 'Daniel Minahan', '0'),
	('1', '7', 'You Win or You Die', '29-May-11', '9.2', '27556', '"Robert has been injured while hunting and is dying. Jon and the others finally take their vows to the Night\'s Watch. A man, sent by Robert, is captured for trying to poison Daenerys. Furious, Drogo vows to attack the Seven Kingdoms."', 'David Benioff', 'D.B. Weiss', 'Sean Bean', 'Mark Addy', 'Nikolaj Coster-Waldau', '21', '27', '2.4', '58', 'Daniel Minahan', '0'),
	('1', '8', 'The Pointy End', '5-Jun-11', '9', '25645', 'The Lannisters press their advantage over the Starks; Robb rallies his father\'s northern allies and heads south to war; The White Walkers attack the Wall; Tyrion returns to his father with some new friends.', 'David Benioff', 'D.B. Weiss', 'Sean Bean', 'Michelle Fairley', 'Lena Headey', '20', '26', '2.72', '59', 'Daniel Minahan', '0'),
	('1', '9', 'Baelor', '12-Jun-11', '9.6', '36217', 'Robb goes to war against the Lannisters. Jon finds himself struggling on deciding if his place is with Robb or the Night\'s Watch. Drogo has fallen ill from a fresh battle wound. Daenerys is desperate to save him.', 'David Benioff', 'D.B. Weiss', 'Sean Bean', 'Michelle Fairley', 'Nikolaj Coster-Waldau', '30', '29', '2.66', '57', 'Alan Taylor', '0'),
	('1', '10', 'Fire and Blood', '19-Jun-11', '9.5', '31789', 'Robb vows to get revenge on the Lannisters. Jon must officially decide if his place is with Robb or the Night\'s Watch. Daenerys says her final goodbye to Drogo.', 'David Benioff', 'D.B. Weiss', 'Sean Bean', 'Michelle Fairley', 'Nikolaj Coster-Waldau', '34', '29', '3.04', '53', 'Alan Taylor', '0'),
	('2', '1', 'The North Remembers', '1-Apr-12', '8.8', '24837', 'Tyrion arrives at King\'s Landing to take his father\'s place as Hand of the King. Stannis Baratheon plans to take the Iron Throne for his own. Robb tries to decide his next move in the war. The Night\'s Watch arrive at the house of Craster.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Nikolaj Coster-Waldau', '22', '29', '3.86', '53', 'Alan Taylor', '0'),
	('2', '2', 'The Night Lands', '8-Apr-12', '8.5', '23458', '"Arya makes friends with Gendry. Tyrion tries to take control of the Small Council. Theon arrives at his home, Pyke, in order to persuade his father into helping Robb with the war. Jon tries to investigate Craster\'s secret."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Emilia Clarke', '19', '25', '3.76', '54', 'Alan Taylor', '0'),
	('2', '3', 'What Is Dead May Never Die', '15-Apr-12', '8.8', '23178', 'Tyrion tries to see who he can trust in the Small Council. Catelyn visits Renly to try and persuade him to join Robb in the war. Theon must decide if his loyalties lie with his own family or with Robb.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Michelle Fairley', '15', '25', '3.77', '53', 'Alik Sakharov', '0'),
	('2', '4', 'Garden of Bones', '22-Apr-12', '8.8', '22415', '"Lord Baelish arrives at Renly\'s camp just before he faces off against Stannis. Daenerys and her company are welcomed into the city of Qarth. Arya, Gendry, and Hot Pie find themselves imprisoned at Harrenhal."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Michelle Fairley', 'Emilia Clarke', '19', '24', '3.65', '51', 'David Petrarca', '0'),
	('2', '5', 'The Ghost of Harrenhal', '29-Apr-12', '8.8', '22603', '"Tyrion investigates a secret weapon that King Joffrey plans to use against Stannis. Meanwhile, as a token for saving his life, Jaqen H\'ghar offers to kill three people that Arya chooses."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Michelle Fairley', '14', '25', '3.9', '55', 'David Petrarca', '0'),
	('2', '6', 'The Old Gods and the New', '6-May-12', '9.1', '23612', '"Theon seizes control of Winterfell. Jon captures a wildling, named Ygritte. The people of King\'s Landing begin to turn against King Joffrey. Daenerys looks to buy ships to sail for the Seven Kingdoms."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Michelle Fairley', '20', '25', '3.88', '54', 'David Nutter', '0'),
	('2', '7', 'A Man Without Honor', '13-May-12', '8.9', '23003', 'Bran and Rickon have escaped Winterfell. Theon tries to hunt them down. Daenerys\' dragons have been stolen. Jon travels through the wilderness with Ygritte as his prisoner. Sansa has bled and is now ready to have Joffrey\'s children.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Nikolaj Coster-Waldau', '14', '24', '3.69', '56', 'David Nutter', '0'),
	('2', '8', 'The Prince of Winterfell', '20-May-12', '8.8', '22729', '"Stannis is just days from King\'s Landing. Tyrion prepares for his arrival. Jon and Qhorin are taken prisoner by the wildlings. Catelyn is arrested for releasing Jaime. Arya, Gendry, and Hot Pie plan to escape from Harrenhal."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Nikolaj Coster-Waldau', '13', '25', '3.86', '54', 'Alan Taylor', '0'),
	('2', '9', 'Blackwater', '27-May-12', '9.7', '39643', 'Stannis Baratheon\'s fleet and army arrive at King\'s Landing and the battle for the city begins. Cersei plans for her and her children\'s future.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Charles Dance', '34', '24', '3.38', '55', 'Neil Marshall', '0'),
	('2', '10', 'Valar Morghulis', '3-Jun-12', '9.4', '28089', 'Joffrey puts Sansa aside for Margaery Tyrell. Robb marries Talisa Maegyr. Jon prepares to meet Mance Rayder. Arya says farewell to Jaqen H\'ghar. Daenerys tries to rescue her dragons.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Nikolaj Coster-Waldau', '27', '24', '4.2', '64', 'Alan Taylor', '0'),
	('3', '1', 'Valar Dohaeris', '31-Mar-13', '8.8', '24808', '"Jon is brought before Mance Rayder, the King Beyond the Wall, while the Night\'s Watch survivors retreat south. In King\'s Landing, Tyrion asks for his reward. Littlefinger offers Sansa a way out."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Emilia Clarke', '19', '36', '4.37', '55', 'Daniel Minahan', '0'),
	('3', '2', '"Dark Wings, Dark Words"', '7-Apr-13', '8.6', '22468', '"Bran and company meet Jojen and Meera Reed. Arya, Gendry, and Hot Pie meet the Brotherhood. Jaime travels through the wilderness with Brienne. Sansa confesses her true feelings about Joffery to Margaery."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '18', '30', '4.27', '56', 'Daniel Minahan', '0'),
	('3', '3', 'Walk of Punishment', '14-Apr-13', '8.9', '22678', 'Robb and Catelyn arrive at Riverrun for Lord Hoster Tully\'s funeral. Tywin names Tyrion the new Master of Coin. Arya says goodbye to Hot Pie. The Night\'s Watch returns to Craster\'s. Brienne and Jaime are taken prisoner.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '21', '29', '4.72', '56', 'David Benioff', '0'),
	('3', '4', 'And Now His Watch Is Ended', '21-Apr-13', '9.6', '30931', 'Jaime mopes over his lost hand. Cersei is growing uncomfortable with the Tyrells. The Night\'s Watch is growing impatient with Craster. Daenerys buys the Unsullied.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '25', '28', '4.87', '53', 'Alex Graves', '0'),
	('3', '5', 'Kissed by Fire', '28-Apr-13', '9', '23110', '"Robb\'s army is falling apart. Jaime reveals a story, to Brienne, that he has never told anyone. Jon breaks his vows. The Hound is granted his freedom. The Lannisters hatch a new plan."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '15', '30', '5.35', '57', 'Alex Graves', '0'),
	('3', '6', 'The Climb', '5-May-13', '8.8', '22978', 'Jon and the wildlings scale the Wall. The Brotherhood sells Gendry to Melisandre. Robb does what he can to win back the Freys. Tyrion tells Sansa about their engagement.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '13', '27', '5.5', '53', 'Alik Sakharov', '0'),
	('3', '7', 'The Bear and the Maiden Fair', '12-May-13', '8.7', '22223', 'Jon and the wildlings travel south of the Wall. Talisa tells Robb that she\'s pregnant. Arya runs away from the Brotherhood. Daenerys arrives at Yunkai. Jaime leaves Brienne behind at Harrenhal.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Emilia Clarke', '19', '27', '4.84', '58', 'Michelle MacLaren', '0'),
	('3', '8', 'Second Sons', '19-May-13', '9', '22800', 'Daenerys tries to persuade the Second Sons to join her against Yunkai. Stannis releases Davos from the dungeons. Sam and Gilly are attacked by a White Walker. Sansa and Tyrion wed.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Emilia Clarke', '16', '30', '5.13', '56', 'Michelle MacLaren', '0'),
	('3', '9', 'The Rains of Castamere', '2-Jun-13', '9.9', '86759', 'Robb and Catelyn arrive at the Twins for the wedding. Jon is put to the test to see where his loyalties truly lie. Bran\'s group decides to split up. Daenerys plans an invasion of Yunkai.', 'George R.R. Martin', 'David Benioff', 'Emilia Clarke', 'Kit Harington', 'Richard Madden', '106', '29', '5.22', '51', 'David Nutter', '0'),
	('3', '10', 'Mhysa', '9-Jun-13', '9.2', '25807', 'Bran and company travel beyond the Wall. Sam returns to Castle Black. Jon says goodbye to Ygritte. Jaime returns to King\'s Landing. The Night\'s Watch asks for help from Stannis.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '21', '29', '5.39', '63', 'David Nutter', '0'),
	('4', '1', 'Two Swords', '6-Apr-14', '9.1', '29302', '"Tyrion welcomes a guest to King\'s Landing. At Castle Black, Jon stands trial. Daenerys is pointed to Meereen, the mother of all slave cities. Arya runs into an old enemy."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '23', '38', '6.64', '58', 'D.B. Weiss', '0'),
	('4', '2', 'The Lion and the Rose', '13-Apr-14', '9.7', '45860', 'Joffrey and Margaery\'s wedding has come. Tyrion breaks up with Shae. Ramsay tries to prove his worth to his father. Bran and company find a Weirwood tree.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '30', '34', '6.31', '52', 'Alex Graves', '0'),
	('4', '3', 'Breaker of Chains', '20-Apr-14', '8.9', '24709', 'Tyrion is arrested for the murder of Joffrey and awaits trial. Sansa escapes King\'s Landing. Sam sends Gilly to Mole\'s Town as the Night\'s Watch finds itself in a tight spot. Meereen challenges Daenerys.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '15', '32', '6.59', '57', 'Alex Graves', '0'),
	('4', '4', 'Oathkeeper', '27-Apr-14', '8.8', '23734', 'Jaime entrusts a task to Brienne. Daenerys frees Meereen. Jon is given permission to lead a group of Night\'s Watchmen to Craster\'s Keep. Bran and company are taken hostage.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '25', '32', '6.95', '55', 'Michelle MacLaren', '0'),
	('4', '5', 'First of His Name', '4-May-14', '8.7', '22964', 'Tommen is crowned King of the Seven Kingdoms. Cersei builds her case against Tyrion. Sansa and Lord Baelish arrive at the Eyrie. The Night\'s Watch attacks Craster\'s Keep.', 'George R.R. Martin', 'David Benioff', 'Nikolaj Coster-Waldau', 'Lena Headey', 'Emilia Clarke', '19', '31', '7.16', '53', 'Michelle MacLaren', '0'),
	('4', '6', 'The Laws of Gods and Men', '11-May-14', '9.7', '42269', 'Tyrion\'s trial has come. Yara and her troops storm the Dreadfort to free Theon. Daenerys meets Hizdar zo Loraq. Stannis makes a deal with the Iron Bank of Braavos.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '42', '29', '6.4', '51', 'Alik Sakharov', '0'),
	('4', '7', 'Mockingbird', '18-May-14', '9.1', '25582', 'Tyrion tries to find a champion. Daenerys sleeps with Daario. The Hound becomes wounded. Jon\'s advice is ignored at Castle Black. Brienne and Podrick receive a tip on Arya\'s whereabouts.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '19', '27', '7.2', '51', 'Alik Sakharov', '0'),
	('4', '8', 'The Mountain and the Viper', '1-Jun-14', '9.7', '45935', '"Theon helps Ramsay seize Moat Cailin. The wildlings attack Mole\'s Town. Sansa comes up with a story to protect Lord Baelish. Daenerys finds out a secret about Jorah Mormont. Oberyn Martell faces Gregor Clegane, the Mountain."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '58', '28', '7.17', '52', 'Alex Graves', '0'),
	('4', '9', 'The Watchers on the Wall', '8-Jun-14', '9.6', '38665', 'The battle between the Night\'s Watch and the wildlings has come.', 'George R.R. Martin', 'David Benioff', 'Kit Harington', 'John Bradley', 'Hannah Murray', '46', '27', '6.95', '51', 'Neil Marshall', '0'),
	('4', '10', 'The Children', '15-Jun-14', '9.7', '37976', '"Jon makes an important decision. Daenerys experiences new consequences. Brienne and Podrick have an unexpected encounter. Bran achieves a goal, while Tyrion makes an important discovery."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '41', '26', '7.09', '65', 'Alex Graves', '0'),
	('5', '1', 'The Wars to Come', '12-Apr-15', '8.5', '26063', '"Cersei and Jaime adjust to a world without Tywin. Tyrion and Varys arrive at Pentos. In Meereen, a new enemy emerges. Jon is caught between two kings."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '28', '45', '8', '53', 'Michael Slovis', '0'),
	('5', '2', 'The House of Black and White', '19-Apr-15', '8.5', '22996', 'Arya arrives in Braavos. Jaime takes on a secret mission. Ellaria Sand seeks revenge for Oberyn\'s death. Stannis makes Jon a generous offer as the Night\'s Watch elects a new Lord Commander. Daenerys is faced with a difficult decision.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '17', '36', '6.81', '56', 'Michael Slovis', '0'),
	('5', '3', 'High Sparrow', '26-Apr-15', '8.5', '22275', 'Tommen and Margaery wed. Arya has trouble adapting to her new life. Littlefinger reveals his plans to Sansa. Jon gives his first orders as Lord Commander. Tyrion and Varys arrive in Volantis.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Kit Harington', '18', '36', '6.71', '60', 'Mark Mylod', '0'),
	('5', '4', 'Sons of the Harpy', '3-May-15', '8.7', '22877', '"Jorah Mormont sets sail alongside his prisoner, Tyrion. Cersei makes a move against the Tyrells. Jaime and Bronn sneak into Dorne. Ellaria and the Sand Snakes make their plans. Melisandre tempts Jon. The Harpies attack."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '19', '35', '6.82', '51', 'Mark Mylod', '0'),
	('5', '5', 'Kill the Boy', '10-May-15', '8.6', '23165', 'Daenerys arrests the heads of Meereen\'s great families. Jon makes a difficult decision. Theon is forced to face Sansa. Stannis rides south. Tyrion and Jorah enter the ruins of Old Valyria.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Emilia Clarke', 'Kit Harington', '20', '35', '6.56', '57', 'Jeremy Podeswa', '0'),
	('5', '6', '"Unbowed, Unbent, Unbroken"', '17-May-15', '8', '26236', 'Arya is put to the test. Tyrion and Jorah are captured by slavers. Loras Tyrell is judged by the Sparrows. Jaime and Bronn face the Sand Snakes. Sansa marries Ramsay Bolton.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '43', '37', '6.24', '54', 'Jeremy Podeswa', '0'),
	('5', '7', 'The Gift', '24-May-15', '9', '25303', 'Jon heads east as trouble begins to stir for Sam and Gilly at Castle Black. Sansa asks Theon for help. Tyrion and Jorah are sold as slaves. Cersei savors her triumph over the Tyrells as new plots are developed in the shadows.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '16', '37', '5.4', '59', 'Miguel Sapochnik', '0'),
	('5', '8', 'Hardhome', '31-May-15', '9.9', '87059', 'Tyrion advises Daenerys. Sansa forces Theon to tell her a secret. Cersei remains stubborn. Arya meets her first target. Jon and Tormund meet with the wildling elders.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Lena Headey', 'Emilia Clarke', '89', '36', '7.01', '61', 'Miguel Sapochnik', '0'),
	('5', '9', 'The Dance of Dragons', '7-Jun-15', '9.5', '38099', 'Jon and the wildlings return to Castle Black. Jaime meets with Doran Martell. Stannis makes a hard choice. Arya runs into Meryn Trant. Daenerys attends the grand reopening of the fighting pits.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Emilia Clarke', '53', '34', '7.14', '52', 'David Nutter', '0'),
	('5', '10', 'Mother\'s Mercy', '14-Jun-15', '9.1', '36939', 'Stannis arrives at Winterfell. Tyrion runs Meereen as Daario and Jorah go after Daenerys. Jaime and Myrcella leave Dorne. Jon sends Sam and Gilly to Oldtown. Arya challenges the Many-Faced God. Cersei confesses her sins.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '110', '35', '8.11', '60', 'David Nutter', '0'),
	('6', '1', 'The Red Woman', '24-Apr-16', '8.5', '35873', 'The fate of Jon Snow is revealed. Daenerys is brought before Khal Moro. Tyrion gets used to living in Meereen. Ramsay sends his dogs after Theon and Sansa. Ellaria and the Sand Snakes make their move. Cersei mourns for Myrcella.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '64', '52', '7.94', '50', 'Jeremy Podeswa', '0'),
	('6', '2', 'Home', '1-May-16', '9.4', '42207', 'Bran trains with the Three-Eyed Raven. Tommen meets with Cersei. Tyrion makes a bold move. Theon leaves while at Pyke new issues arise. Ramsay\'s brother is born. Davos asks Melisandre for a miracle.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '51', '49', '7.29', '54', 'Jeremy Podeswa', '0'),
	('6', '3', 'Oathbreaker', '8-May-16', '8.7', '30065', '"Daenerys arrives at Vaes Dothrak. Sam and Gilly sail for Horn Hill. Arya trains as No One. Varys finds information on the Sons of the Harpy. Ramsay receives a gift. Tommen meets with the High Sparrow. At Castle Black, a miracle occurs."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '26', '48', '7.28', '52', 'Daniel Sackheim', '0'),
	('6', '4', 'Book of the Stranger', '15-May-16', '9.1', '32360', 'Sansa arrives at Castle Black. Tyrion makes a deal with the slave masters. Jorah and Daario sneak into Vaes Dothrak. Ramsay sends a letter to Jon. Theon arrives at Pyke. Cersei and Olenna Tyrell plot against the High Sparrow.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '29', '47', '7.82', '59', 'Daniel Sackheim', '0'),
	('6', '5', 'The Door', '22-May-16', '9.7', '63527', 'Sansa and Jon make plans. Arya is given another chance to prove herself. Jorah confesses a secret to Daenerys. Tyrion meets with a red priestess. Yara finds her rule tested. Bran discovers the origin of the White Walkers.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Emilia Clarke', 'Kit Harington', '53', '46', '7.89', '57', 'Jack Bender', '0'),
	('6', '6', 'Blood of My Blood', '29-May-16', '8.4', '29884', 'Bran and Meera find a new ally. Gilly meets Sam\'s family. Arya makes a difficult choice. The Lannisters and Tyrells march against the High Sparrow.', 'George R.R. Martin', 'David Benioff', 'Nikolaj Coster-Waldau', 'Lena Headey', 'Emilia Clarke', '36', '40', '6.71', '52', 'Jack Bender', '0'),
	('6', '7', 'The Broken Man', '5-Jun-16', '8.6', '29021', 'Jon and Sansa gather troops. Jaime arrives at Riverrun. Olenna Tyrell plans to leave King\'s Landing. Theon and Yara plan a destination. Arya makes plans to leave.', 'George R.R. Martin', 'David Benioff', 'Nikolaj Coster-Waldau', 'Lena Headey', 'Kit Harington', '28', '43', '7.8', '51', 'Mark Mylod', '0'),
	('6', '8', 'No One', '12-Jun-16', '8.4', '33040', 'Brienne arrives at Riverrun. Arya seeks shelter. Jaime meets with Edmure Tully. Cersei challenges the Faith. Sandor Clegane hunts for revenge. Tyrion faces the consequences of earlier decisions.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '68', '43', '7.6', '59', 'Mark Mylod', '0'),
	('6', '9', 'Battle of the Bastards', '19-Jun-16', '9.9', '185033', 'Jon and Sansa face Ramsay Bolton on the fields of Winterfell. Daenerys strikes back at her enemies. Theon and Yara arrive in Meereen.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Kit Harington', 'Emilia Clarke', '253', '49', '7.66', '60', 'Miguel Sapochnik', '0'),
	('6', '10', 'The Winds of Winter', '26-Jun-16', '9.9', '128642', 'Cersei and Loras Tyrell stand trial by the gods. Daenerys prepares to set sail for Westeros. Davos confronts Melisandre. Sam and Gilly arrive in the Citadel. Bran discovers a long-kept secret. Lord Frey has an uninvited guest.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '182', '46', '8.89', '68', 'Miguel Sapochnik', '0'),
	('7', '1', 'Dragonstone', '16-Jul-17', '8.6', '46297', '"Jon organizes the North\'s defenses. Cersei tries to even the odds. Daenerys comes home. Arya reminds the Freys ""the North remembers."" Sam adapts to life in Oldtown. The Night King makes his way south."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '88', '66', '10.11', '59', 'Jeremy Podeswa', '0'),
	('7', '2', 'Stormborn', '23-Jul-17', '8.9', '39903', 'Daenerys receives an unexpected visitor. Jon faces resistance. Tyrion plans the conquest of Westeros. Cersei gathers her allies. Arya has a reunion with old friends. Sam risks his career and life.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '54', '55', '9.27', '59', 'Mark Mylod', '0'),
	('7', '3', 'The Queen\'s Justice', '30-Jul-17', '9.2', '41611', 'Jon and Daenerys finally meet. Cersei gains a new ally. Sansa receives an unexpected visitor. Sam is confronted for his actions.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '49', '53', '9.25', '63', 'Mark Mylod', '0'),
	('7', '4', 'The Spoils of War', '6-Aug-17', '9.8', '78989', 'Daenerys takes matters into her own hands. Arya reaches her destination. Jaime and Bronn collect the spoils from the war with the Tyrells.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '94', '53', '10.17', '50', 'Matt Shakman', '0'),
	('7', '5', 'Eastwatch', '13-Aug-17', '8.8', '39682', 'Daenerys demands loyalty from the surviving Lannister soldiers; Jon heeds Bran\'s warning about White Walkers on the move; Cersei vows to vanquish anyone or anything that stands in her way.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '53', '51', '10.72', '59', 'Matt Shakman', '0'),
	('7', '6', 'Beyond the Wall', '20-Aug-17', '9', '57960', 'Jon and his team go beyond the wall to capture a wight. Daenerys has to make a tough decision.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Emilia Clarke', 'Kit Harington', '181', '52', '10.24', '70', 'Alan Taylor', '0'),
	('7', '7', 'The Dragon and the Wolf', '27-Aug-17', '9.4', '57484', '"Everyone meets in King\'s Landing to discuss the fate of the realm. In Winterfell, Sansa confronts Arya. Sam reaches Winterfell, where he and Bran discover a shocking secret about Jon Snow."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '133', '48', '12.07', '80', 'Jeremy Podeswa', '0'),
	('8', '1', 'Winterfell', '14-Apr-19', '7.6', '121831', 'Jon and Daenerys arrive in Winterfell and are met with skepticism. Sam learns about the fate of his family. Cersei gives Euron the reward he aims for. Theon follows his heart.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '655', '71', '11.76', '54', 'David Nutter', '0'),
	('8', '2', 'A Knight of the Seven Kingdoms', '21-Apr-19', '7.9', '119961', 'Jaime faces judgment and Winterfell prepares for the battle to come.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Emilia Clarke', '537', '59', '10.29', '58', 'David Nutter', '0'),
	('8', '3', 'The Long Night', '28-Apr-19', '7.5', '200283', 'The Night King and his army have arrived at Winterfell and the great battle begins.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Emilia Clarke', '3749', '71', '12.02', '82', 'Miguel Sapochnik', '0'),
	('8', '4', 'The Last of the Starks', '5-May-19', '5.5', '152769', 'The Battle of Winterfell is over and a new chapter for Westeros begins.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '2277', '62', '11.8', '78', 'David Nutter', '0'),
	('8', '5', 'The Bells', '12-May-19', '6', '177957', 'Forces have arrived at King\'s Landing for the final battle.', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '3906', '61', '12.48', '78', 'Miguel Sapochnik', '0'),
	('8', '6', 'The Iron Throne', '19-May-19', '4.1', '220581', '"In the aftermath of the devastating attack on King\'s Landing, Daenerys must face the survivors."', 'George R.R. Martin', 'David Benioff', 'Peter Dinklage', 'Nikolaj Coster-Waldau', 'Lena Headey', '7358', '70', '13.61', '80', 'David Benioff', '0');



INSERT INTO casas (Chrcter, Actor/ess, Episodes_appeared, First_appearance, Last_appearance) VALUES
	('Tyrion Lannister', 'Peter Dinklage', '67', '2011', '2019'),
	('Cersei Lannister', 'Lena Headey', '62', '2011', '2019'),
	('Daenerys Targaryen', 'Emilia Clarke', '62', '2011', '2019'),
	('Jon Snow', 'Kit Harington', '62', '2011', '2019'),
	('Sansa Stark', 'Sophie Turner', '59', '2011', '2019'),
	('Arya Stark', 'Maisie Williams', '59', '2011', '2019'),
	('Jaime Lannister', 'Nikolaj Coster-Waldau', '55', '2011', '2019'),
	('Jorah Mormont', 'Iain Glen', '52', '2011', '2019'),
	('Samwell Tarly', 'John Bradley', '48', '2011', '2019'),
	('Theon Greyjoy', 'Alfie Allen', '47', '2011', '2019'),
	('Lord Varys', 'Conleth Hill', '46', '2011', '2019'),
	('Davos Seaworth', 'Liam Cunningham', '42', '2012', '2019'),
	('Brienne of Tarth', 'Gwendoline Christie', '42', '2012', '2019'),
	('Petyr \'Littlefinger\' Baelish', 'Aidan Gillen', '41', '2011', '2017'),
	('Bran Stark', 'Isaac Hempstead Wright', '40', '2011', '2019'),
	('Sandor \'The Hound\' Clegane', 'Rory McCann', '38', '2011', '2019'),
	('Missandei', 'Nathalie Emmanuel', '38', '2013', '2019'),
	('Bronn', 'Jerome Flynn', '37', '2011', '2019'),
	('Podrick Payne', 'Daniel Portman', '35', '2012', '2019'),
	('Grey Worm', 'Jacob Anderson', '34', '2013', '2019'),
	('Eddison Tollett', 'Ben Crompton', '34', '2012', '2019'),
	('Tormund Giantsbane', 'Kristofer Hivju', '33', '2013', '2019'),
	('Grand Maester Pycelle', 'Julian Glover', '31', '2011', '2016'),
	('Melisandre', 'Carice van Houten', '29', '2012', '2019'),
	('Tywin Lannister', 'Charles Dance', '27', '2011', '2015'),
	('Gilly', 'Hannah Murray', '27', '2012', '2019'),
	('Margaery Tyrell', 'Natalie Dormer', '26', '2012', '2016'),
	('Joffrey Baratheon', 'Jack Gleeson', '26', '2011', '2014'),
	('Catelyn Stark', 'Michelle Fairley', '26', '2011', '2016'),
	('Barristan Selmy', 'Ian McElhinney', '25', '2011', '2015'),
	('Stannis Baratheon', 'Stephen Dillane', '24', '2012', '2015'),
	('Gendry', 'Joe Dempsie', '24', '2011', '2019'),
	('Hodor', 'Kristian Nairn', '23', '2011', '2016'),
	('Qyburn', 'Anton Lesser', '22', '2013', '2019'),
	('Grenn', 'Mark Stanley', '22', '2011', '2014'),
	('Robb Stark', 'Richard Madden', '22', '2011', '2016'),
	('Loras Tyrell', 'Finn Jones', '21', '2011', '2016'),
	('Shae', 'Sibel Kekilli', '20', '2011', '2014'),
	('Ramsay Bolton', 'Iwan Rheon', '20', '2013', '2016'),
	('Roose Bolton', 'Michael McElhatton', '20', '2012', '2016'),
	('Alliser Thorne', 'Owen Teale', '19', '2011', '2016'),
	('Daario Naharis', 'Michiel Huisman', '18', '2014', '2016'),
	('Olenna Tyrell', 'Diana Rigg', '18', '2013', '2017'),
	('Tommen Baratheon', 'Dean-Charles Chapman', '18', '2013', '2016'),
	('Ygritte', 'Rose Leslie', '17', '2012', '2014'),
	('Jaqen H\'ghar', 'Tom Wlaschiha', '17', '2012', '2016'),
	('Gregor \'The Mountain\' Clegane', 'Hafþór Júlíus Björnsson', '17', '2014', '2019'),
	('Olly', 'Brenock O\'Connor', '17', '2014', '2016'),
	('Meryn Trant', 'Ian Beattie', '17', '2011', '2015'),
	('Osha', 'Natalia Tena', '16', '2011', '2016'),
	('Yara Greyjoy', 'Gemma Whelan', '16', '2012', '2019'),
	('Meera Reed', 'Ellie Kendrick', '16', '2013', '2017'),
	('Wun Wun', 'Ian Whyte', '16', '2011', '2019'),
	('Lancel Lannister', 'Eugene Simon', '16', '2011', '2016'),
	('Janos Slynt', 'Dominic Carter', '15', '2011', '2015'),
	('Maester Luwin', 'Donald Sumpter', '14', '2011', '2012'),
	('Ros', 'Esmé Bianco', '14', '2011', '2013'),
	('Rickon Stark', 'Art Parkinson', '14', '2011', '2016'),
	('Othell Yarwyck', 'Brian Fortune', '14', '2011', '2016'),
	('Ellaria Sand', 'Indira Varma', '13', '2014', '2017'),
	('Rodrik Cassel', 'Ron Donachie', '13', '2011', '2012'),
	('Beric Dondarrion', 'Richard Dormer', '13', '2013', '2019'),
	('Mace Tyrell', 'Roger Ashton-Griffiths', '13', '2014', '2016'),
	('Yohn Royce', 'Rupert Vansittart', '13', '2014', '2019'),
	('Pypar', 'Josef Altin', '13', '2011', '2014'),
	('Irri', 'Amrita Acharia', '13', '2011', '2012'),
	('High Sparrow', 'Jonathan Pryce', '12', '2015', '2016'),
	('Jeor Mormont', 'James Cosmo', '12', '2011', '2013'),
	('Maester Wolkan', 'Richard Rycroft', '12', '2016', '2019'),
	('Kevan Lannister', 'Ian Gelder', '12', '2011', '2016'),
	('Rast', 'Luke Barnes', '12', '2011', '2014'),
	('Hot Pie', 'Ben Hawkey', '12', '2011', '2017'),
	('Talisa Stark', 'Oona Chaplin', '11', '2012', '2013'),
	('Maester Aemon', 'Peter Vaughan', '11', '2011', '2015'),
	('The Waif', 'Faye Marsay', '11', '2015', '2016'),
	('Doreah', 'Roxanne McKee', '11', '2011', '2012'),
	('Qhono', 'Staz Nair', '11', '2016', '2019'),
	('Eddard \'Ned\' Stark', 'Sean Bean', '10', '2011', '2011'),
	('Thoros of Myr', 'Paul Kaye', '10', '2013', '2017'),
	('Selyse Baratheon', 'Tara Fitzgerald', '10', '2013', '2015'),
	('Jojen Reed', 'Thomas Brodie-Sangster', '10', '2013', '2014'),
	('Shireen Baratheon', 'Kerry Ingram', '10', '2013', '2015'),
	('Bowen Marsh', 'Michael Condron', '10', '2015', '2016'),
	('Khal Drogo', 'Jason Momoa', '10', '2011', '2012'),
	('Euron Greyjoy', 'Pilou Asbæk', '9', '2016', '2019'),
	('Edmure Tully', 'Tobias Menzies', '9', '2013', '2019'),
	('Tyene Sand', 'Rosabell Laurenti Sellers', '9', '2015', '2017'),
	('Lyanna Mormont', 'Bella Ramsey', '9', '2016', '2019'),
	('Robin Arryn', 'Lino Facioli', '9', '2011', '2019'),
	('Renly Baratheon', 'Gethin Anthony', '8', '2011', '2012'),
	('Locke', 'Noah Taylor', '8', '2013', '2014'),
	('Obara Sand', 'Keisha Castle-Hughes', '8', '2015', '2017'),
	('Hizdahr zo Loraq', 'Joel Fry', '8', '2014', '2015'),
	('Nymeria Sand', 'Jessica Henwick', '8', '2015', '2017'),
	('Septa Unella', 'Hannah Waddingham', '8', '2015', '2016'),
	('Myranda', 'Charlotte Hope', '8', '2013', '2016'),
	('Kovarro', 'Steven Cole', '8', '2012', '2012'),
	('Tommen Baratheon', 'Callum Wharry', '8', '2011', '2012'),
	('Myrcella Baratheon', 'Aimee Richardson', '8', '2011', '2012'),
	('Marei', 'Josephine Gillan', '8', '2012', '2019'),
	('Robert Baratheon', 'Mark Addy', '7', '2011', '2011'),
	('Oberyn Martell', 'Pedro Pascal', '7', '2014', '2014'),
	('Yoren', 'Francis Magee', '7', '2011', '2012'),
	('Brynden \'Blackfish\' Tully', 'Clive Russell', '7', '2013', '2016'),
	('Olyvar', 'Will Tudor', '7', '2013', '2015'),
	('Rakharo', 'Elyes Gabel', '7', '2011', '2012'),
	('Bernadette', 'Sara Dylan', '7', '2012', '2017'),
	('Walder Frey', 'David Bradley', '6', '2011', '2017'),
	('Benjen Stark', 'Joseph Mawle', '6', '2011', '2017'),
	('Orell', 'Mackenzie Crook', '6', '2013', '2013'),
	('Areo Hotah', 'Deobia Oparei', '6', '2015', '2016'),
	('Septa Mordane', 'Susan Brown', '6', '2011', '2011'),
	('Black Walder Rivers', 'Tim Plester', '6', '2013', '2016'),
	('Qotho', 'Dar Salim', '6', '2011', '2011'),
	('Dontos Hollard', 'Tony Way', '6', '2012', '2014'),
	('Myrcella Baratheon', 'Nell Tiger Free', '6', '2015', '2016'),
	('Anguy', 'Philip McGinley', '6', '2013', '2013'),
	('High Septon', 'Paul Bentley', '6', '2013', '2015'),
	('Alys Karstark', 'Megan Parkinson', '6', '2016', '2019'),
	('Night\'s Watch Officer', 'Dennis McKeever', '6', '2011', '2013'),
	('Viserys Targaryen', 'Harry Lloyd', '5', '2011', '2011'),
	('Jory Cassel', 'Jamie Sives', '5', '2011', '2011'),
	('Lysa Arryn', 'Kate Dickie', '5', '2011', '2014'),
	('Mance Rayder', 'Ciarán Hinds', '5', '2013', '2015'),
	('Craster', 'Robert Pugh', '5', '2012', '2013'),
	('Doran Martell', 'Alexander Siddig', '5', '2015', '2016'),
	('Xaro Xhoan Daxos', 'Nonso Anozie', '5', '2012', '2012'),
	('Randyll Tarly', 'James Faulkner', '5', '2016', '2017'),
	('Robett Glover', 'Tim McInnerny', '5', '2016', '2017'),
	('Rickard Karstark', 'John Stahl', '5', '2012', '2013'),
	('Dagmer Cleftjaw', 'Ralph Ineson', '5', '2012', '2012'),
	('Walda Bolton', 'Elizabeth Webster', '5', '2014', '2016'),
	('Trystane Martell', 'Toby Sebastian', '5', '2015', '2016'),
	('The Night King', 'Vladimir \'Furdo\' Furdik', '5', '2016', '2019'),
	('Archmaester Ebrose', 'Jim Broadbent', '4', '2017', '2017'),
	('Tycho Nestoris', 'Mark Gatiss', '4', '2014', '2017'),
	('Balon Greyjoy', 'Patrick Malahide', '4', '2012', '2016'),
	('Pyat Pree', 'Ian Hanmore', '4', '2012', '2012'),
	('Styr', 'Yuri Kolokolnikov', '4', '2014', '2014'),
	('Yezzan zo Qaggaz', 'Enzo Cilenti', '4', '2015', '2016'),
	('Karl Tanner', 'Burn Gorman', '4', '2013', '2014'),
	('Ilyn Payne', 'Wilko Johnson', '4', '2011', '2012'),
	('Marillion', 'Emun Elliott', '4', '2011', '2011'),
	('Dickon Tarly', 'Tom Hopper', '4', '2017', '2017'),
	('Qhorin Halfhand', 'Simon Armstrong', '4', '2012', '2012'),
	('Lothar Frey', 'Daniel Tuite', '4', '2016', '2016'),
	('Rorge', 'Andy Beckwith', '4', '2012', '2014'),
	('Lommy Greenhands', 'Eros Vlahos', '4', '2011', '2012'),
	('Matthos Seaworth', 'Kerr Logan', '4', '2012', '2012'),
	('Armeca', 'Sahara Knite', '4', '2011', '2012'),
	('Royal Steward', 'Robert Sterne', '4', '2011', '2011'),
	('Black Lorren', 'Forbes KB', '4', '2012', '2012'),
	('Amory Lorch', 'Fintan McKeown', '4', '2012', '2012'),
	('Biter', 'Gerard Jordan', '4', '2012', '2014'),
	('Young Ned', 'Robert Aramayo', '4', '2016', '2017'),
	('Baby Sam', 'William Nevan Wilson', '4', '2016', '2017'),
	('Baby Sam', 'James Robert Wilson', '4', '2016', '2017'),
	('Timett', 'Tobias Winter', '4', '2011', '2012'),
	('Steelshanks Walton', 'Jamie Michie', '4', '2013', '2013'),
	('Izembaro', 'Richard E. Grant', '3', '2016', '2016'),
	('Lady Crane', 'Essie Davis', '3', '2016', '2016'),
	('Spice King', 'Nicholas Blane', '3', '2012', '2012'),
	('Three-Eyed Raven', 'Max von Sydow', '3', '2016', '2016'),
	('Syrio Forel', 'Miltos Yerolemou', '3', '2011', '2011'),
	('Harrag', 'Brendan Cowell', '3', '2017', '2017'),
	('Salladhor Saan', 'Lucian Msamati', '3', '2012', '2014'),
	('Daario Naharis', 'Ed Skrein', '3', '2013', '2013'),
	('Greatjon Umber', 'Clive Mantle', '3', '2011', '2011'),
	('Camello', 'Kevin Eldon', '3', '2016', '2017'),
	('Harald Karstark', 'Paul Rattray', '3', '2016', '2016'),
	('Giant Wight #2', 'Neil Fingleton', '3', '2014', '2017'),
	('Leaf', 'Kae Alexander', '4', '2016', '2016'),
	('Bobono', 'Leigh Gill', '3', '2016', '2016'),
	('Razdal mo Eraz', 'George Georgiou', '3', '2013', '2016'),
	('Lhara', 'Sarine Sofair', '3', '2014', '2015'),
	('Clarenzo', 'Rob Callender', '3', '2016', '2016'),
	('Thenn Warg', 'Joseph Gatt', '3', '2014', '2014'),
	('Mirri Maz Duur', 'Mia Soteriou', '3', '2011', '2011'),
	('Polliver', 'Andy Kellegher', '3', '2012', '2014'),
	('Alton Lannister', 'Karl Davies', '3', '2012', '2012'),
	('Khal Moro', 'Joseph Naufahu', '3', '2016', '2016'),
	('Ned Umber', 'Harry Grasby', '3', '2017', '2019'),
	('Kraznys mo Nakloz', 'Dan Hildebrand', '3', '2013', '2013'),
	('Mossador', 'Reece Noi', '3', '2014', '2015'),
	('White Walker', 'Ross Mullan', '3', '2012', '2014'),
	('Rattleshirt', 'Edward Dogliani', '3', '2012', '2013'),
	('Vala', 'Meena Rayann', '3', '2015', '2016'),
	('Daisy', 'Maisie Dee', '3', '2012', '2012'),
	('Bathhouse Prostitute', 'Samantha Bentley', '3', '2014', '2015'),
	('Silk King', 'Slavko Juraga', '3', '2012', '2012'),
	('Dothraki Bloodrider #1', 'Diogo Sales', '3', '2016', '2016'),
	('Musician #1', 'Nanna Bryndís Hilmarsdóttir', '3', '2016', '2016'),
	('Dothraki Bloodrider #2', 'Junade Khan', '3', '2016', '2016'),
	('Musician #2', 'Ragnar Þórhallsson', '3', '2016', '2016'),
	('Musician #3', 'Arnar Rosenkranz Hilmarsson', '3', '2016', '2016'),
	('Musician #4', 'Brynjar Leifsson', '3', '2016', '2016'),
	('Loyal Night\'s Watchman #2', 'Robert Fawsitt', '3', '2016', '2016'),
	('Musician #5', 'Kristján Kristjánsson', '3', '2016', '2016'),
	('King\'s Landing Whore', 'Xena Avramidis', '3', '2014', '2015'),
	('Dothraki Woman Having Sex', 'Portia-Valis Volkova', '3', '2015', '2016'),
	('Aggo', 'Chuku Modu', '3', '2016', '2016'),
	('Frances', 'Annette Hannah', '3', '2016', '2017'),
	('Brothel Patron #5', 'Derek Dubery', '3', '2015', '2019'),
	('Hallyne', 'Roy Dotrice', '2', '2012', '2012'),
	('Harry Strickland', 'Marc Rissmann', '2', '2019', '2019'),
	('Illyrio Mopatis', 'Roger Allam', '2', '2011', '2011'),
	('Lem Lemoncloak', 'Jóhannes Haukur Jóhannesson', '2', '2016', '2016'),
	('Smalljon Umber', 'Dean Jagger', '2', '2016', '2016'),
	('Martha', 'Bronte Carmichael', '2', '2019', '2019'),
	('Mord', 'Ciaran Bermingham', '2', '2011', '2011'),
	('Aeron Greyjoy', 'Michael Feast', '2', '2016', '2016'),
	('Dim Dalba', 'Murray McArthur', '2', '2015', '2016'),
	('Belicho Paenymion', 'Eddie Jackson', '2', '2016', '2016'),
	('Fergus', 'Seamus O\'Hara', '2', '2019', '2019'),
	('Gatins', 'Ricky Champ', '2', '2016', '2016'),
	('Teela', 'Bea Glancy', '2', '2019', '2019'),
	('Old Nan', 'Margaret John', '2', '2011', '2011'),
	('The Night King', 'Richard Brake', '3', '2014', '2016'),
	('Morgan', 'Ian Davies', '2', '2016', '2016'),
	('Woman with Elderly Parents', 'Lucy McConnell', '2', '2019', '2019'),
	('Gregor \'The Mountain\' Clegane', 'Conan Stevens', '2', '2011', '2011'),
	('Malko', 'Adewale Akinnuoye-Agbaje', '2', '2015', '2015'),
	('Thin Man', 'Oengus MacNamara', '2', '2015', '2015'),
	('Lothar Frey', 'Tom Brooke', '2', '2013', '2013'),
	('Bianca', 'Eline Powell', '2', '2016', '2016'),
	('Vardis Egen', 'Brendan McCormack', '2', '2011', '2011'),
	('Shagga', 'Mark Lewis Jones', '2', '2011', '2011'),
	('Quaithe', 'Laura Pradelska', '2', '2012', '2012'),
	('Margaery Tyrell Mummer', 'Eva Butterly', '2', '2016', '2016'),
	('Old Woman', 'Stella McCusker', '2', '2015', '2015'),
	('Baby Sam', 'Logan Watson', '2', '2019', '2019'),
	('Hugh of the Vale', 'Jefferson Hall', '2', '2011', '2011'),
	('Morag', 'Deirdre Monaghan', '2', '2014', '2014'),
	('Todder', 'Will O\'Connell', '2', '2013', '2015'),
	('Johnna', 'Ali Lyons', '2', '2015', '2015'),
	('Willa', 'Karla Lyons', '2', '2015', '2015'),
	('Lady Kitty Frey', 'Lucy Hayes', '2', '2016', '2017'),
	('Baby Sam', 'Finn Watson', '2', '2019', '2019'),
	('Lyanna Stark', 'Aisling Franciosi', '2', '2016', '2017'),
	('Village Woman', 'Eileen McCloskey', '2', '2019', '2019'),
	('Farlen', 'Peter Ballance', '2', '2012', '2012'),
	('Donnel Waynwood', 'Alisdair Simpson', '2', '2014', '2014'),
	('Drennan', 'David Coakley', '2', '2012', '2012'),
	('Sissy', 'Jane McGrath', '2', '2014', '2014'),
	('Dosh khaleen High Priestess', 'Souad Faress', '2', '2016', '2016'),
	('Zanrush', 'Gerald Lepkowski', '2', '2016', '2016'),
	('King\'s Landing Whore', 'Emily Diamond', '2', '2011', '2011'),
	('Ornela', 'Hannah John-Kamen', '2', '2016', '2016'),
	('Young Nan', 'Annette Tierney', '2', '2016', '2016'),
	('Kurleket', 'Kevin Keenan', '2', '2011', '2011'),
	('Winterfell Shepherd', 'Donagh Deeney', '2', '2012', '2012'),
	('The Tickler', 'Anthony Morris', '2', '2012', '2012'),
	('Ghita', 'Hattie Gotobed', '2', '2015', '2015'),
	('Wyllis', 'Sam Coleman', '2', '2016', '2016'),
	('Morgan', 'Chris Reilly', '2', '2012', '2014'),
	('Greizhen mo Ullhor', 'Cliff Barry', '2', '2013', '2013'),
	('Mole\'s Town Whore', 'Lois Winstone', '2', '2014', '2014'),
	('Willis Wode', 'Ryan McKenna', '2', '2011', '2011'),
	('Jacks', 'Paul Caddell', '2', '2012', '2012'),
	('Goldcloak', 'Sam Callis', '2', '2012', '2012'),
	('King\'s Landing Rioter #1', 'Reg Wayment', '2', '2012', '2012'),
	('Ternesio Terys', 'Gary Oliver', '2', '2014', '2015'),
	('Moro\'s Wife #2', 'Fola Evans-Akingbola', '2', '2016', '2016'),
	('Master Torturer', 'Michael Shelford', '2', '2013', '2013'),
	('Great Master #1', 'Emilio Doorgasingh', '2', '2014', '2014'),
	('Young Ned Stark', 'Sebastian Croft', '2', '2016', '2016'),
	('Young Rodrik Cassel', 'Fergus Leathem', '2', '2016', '2016'),
	('Mhaegen', 'Antonia Christophers', '2', '2011', '2012'),
	('nan', 'Will Fortune', '2', '2014', '2015'),
	('Mole\'s Town Madam', 'Lu Corfield', '2', '2014', '2014'),
	('Lannister Captain', 'Aiden Condron', '2', '2012', '2012'),
	('Quent', 'Aidan Crowe', '2', '2012', '2012'),
	('Young Benjen Stark', 'Matteo Elezi', '2', '2016', '2016'),
	('Dothraki Widow #1', 'Angelique Fernandez', '2', '2016', '2016'),
	('Stark Guard', 'David Sheehan', '2', '2012', '2012'),
	('Mummer #2', 'Glen Barry', '2', '2016', '2016'),
	('Kayla', 'Pixie Le Knot', '2', '2013', '2014'),
	('Manservant', 'Conor Watters', '2', '2014', '2014'),
	('Mummer #3', 'Brendan O\'Rourke', '2', '2016', '2016'),
	('Tobho Mott', 'Andrew Wilde', '2', '2011', '2012'),
	('Mummer #4', 'Ross Anderson-Doherty', '2', '2016', '2016'),
	('Night\'s Watchman #1', 'Michael Hayes', '2', '2016', '2016'),
	('Dothraki Widow #2', 'Wuese Houston-Jibo', '2', '2016', '2016'),
	('Willem Lannister', 'Timothy Gibbons', '2', '2013', '2013'),
	('Baratheon Soldier #2', 'Jason McLaughlin', '2', '2015', '2015'),
	('Loyal Night\'s Watchman #1', 'Steve Cash', '2', '2016', '2016'),
	('Night\'s Watchman #2', 'Tony Flynn', '2', '2016', '2016'),
	('Night\'s Watchman', 'Michael Hooley', '2', '2016', '2016'),
	('The Mother', 'Em Scribbler', '2', '2015', '2015'),
	('Male Prostitute', 'Dennis Stokes', '2', '2012', '2012'),
	('The Maiden', 'Rebecca Scott', '2', '2015', '2015'),
	('The Crone', 'Rosie Ruthless', '2', '2015', '2015'),
	('Arthur', 'Nathanael Saleh', '2', '2016', '2016'),
	('Little Bird #4', 'Jesse Magee', '2', '2016', '2016'),
	('Little Bird #3', 'Michael Nevin', '2', '2016', '2016'),
	('Little Bird #6', 'Lucy Gallagher', '2', '2016', '2016'),
	('Little Bird #5', 'Iona Clarke', '2', '2016', '2016'),
	('Little Bird #7', 'Fionn Kernan', '2', '2016', '2016'),
	('Three-Eyed Raven', 'Struan Rodger', '2', '2014', '2014'),
	('Joyeuse Frey', 'Kelly Long', '2', '2011', '2013'),
	('Tyrell Lady', 'Sophie Reid', '2', '2013', '2013'),
	('Tommy', 'Tommy Dunne', '2', '2011', '2014'),
	('Leo Lefford', 'Vinnie McCabe', '2', '2011', '2011'),
	('Ironborn #2', 'Robert Render', '2', '2011', '2016'),
	('Brother Ray', 'Ian McShane', '1', '2016', '2016'),
	('Nora', 'Laura Elphinstone', '1', '2019', '2019'),
	('Xela', 'Alexis Raben', '1', '2019', '2019'),
	('Lannister Soldier', 'Matthew Wolf', '1', '2019', '2019'),
	('Karsi', 'Birgitte Hjort Sørensen', '1', '2015', '2015'),
	('Nora\'s Daughter', 'Tipper Seifert-Cleveland', '1', '2019', '2019'),
	('Singing Lannister Soldier', 'Stephen Swift', '1', '2012', '2012'),
	('Northern Sentry', 'Frank Blake', '1', '2019', '2019'),
	('Dying Man', 'Barry McGovern', '1', '2014', '2014'),
	('Loboda', 'Zachary Baharov', '1', '2015', '2015'),
	('Lannister Soldier', 'Ryan McKen', '1', '2019', '2019'),
	('Stark Soldier', 'Danny Kirrane', '1', '2017', '2017'),
	('Unsullied Captain', 'Gabriel Akuwudike', '1', '2019', '2019'),
	('Lannister Soldier', 'Owen Whitelaw', '1', '2019', '2019'),
	('Imry Florent', 'Gordon Mahon', '1', '2012', '2012'),
	('Captain of the Bolton Archers', 'Rory Mullen', '1', '2016', '2016'),
	('Koner', 'Joseph Quinn', '1', '2017', '2017'),
	('Ironborn Lord', 'Noel Harron', '1', '2019', '2019'),
	('Young Woman', 'Rori Hawthorn', '1', '2019', '2019'),
	('Mandon Moore', 'James Doran', '1', '2012', '2012'),
	('Bolton General', 'Mark Tankersley', '1', '2016', '2016'),
	('Northerner in Alley', 'Oliver Devoti', '1', '2019', '2019'),
	('Dornish Prince', 'Toby Osmond', '1', '2019', '2019'),
	('Jhiqui', 'Sarita Piotrowski', '1', '2011', '2011'),
	('Baratheon Officer', 'Kieran Cunningham', '1', '2012', '2012'),
	('Northman Rider', 'David Birkbeck', '1', '2016', '2016'),
	('Melessa Tarly', 'Samantha Spiro', '1', '2016', '2016'),
	('Winterfell Local', 'Breige Roche', '1', '2017', '2017'),
	('Riverlands Lord', 'Andrew Bicknell', '1', '2019', '2019'),
	('Lannister Soldier', 'Jim Tighe', '1', '2019', '2019'),
	('Will', 'Bronson Webb', '1', '2011', '2011'),
	('Captain of the Archers', 'Michael Grennell', '1', '2012', '2012'),
	('Lord of Bones', 'Ross O\'Hennessy', '1', '2015', '2015'),
	('Northman Archer', 'Paul Garrett', '1', '2016', '2016'),
	('Stark Soldier', 'Eamonn Keenan', '1', '2017', '2017'),
	('Lord Une', 'Michael Benbaruk', '1', '2019', '2019'),
	('Mycah', 'Rhodri Hosking', '1', '2011', '2011'),
	('Jon Arryn', 'John Standing', '1', '2011', '2011'),
	('Mero', 'Mark Killeen', '1', '2013', '2013'),
	('Vale Lord', 'Frank Jakeman', '1', '2019', '2019'),
	('Lannister Soldier', 'Luke McQuillan', '1', '2019', '2019'),
	('Waymar Royce', 'Rob Ostlere', '1', '2011', '2011'),
	('Prendahl na Ghezn', 'Ramon Tikaram', '1', '2013', '2013'),
	('Goatherd', 'Philip Arditti', '1', '2014', '2014'),
	('Northern Lord', 'Niall Bishop', '1', '2019', '2019'),
	('King\'s Landing Citizen', 'Nicky Harley', '1', '2019', '2019'),
	('Gared', 'Dermot Keaney', '1', '2011', '2011'),
	('Catspaw Assassin', 'Lalor Roddy', '1', '2011', '2011'),
	('Maester Cressen', 'Oliver Ford Davies', '1', '2012', '2012'),
	('Septon', 'Kenneth Hadley', '1', '2013', '2013'),
	('First Mate', 'Rhodri Miles', '1', '2014', '2014'),
	('Citadel Maester', 'Julian Firth', '1', '2017', '2017'),
	('Wight at Table', 'Javier Botet', '1', '2019', '2019'),
	('King\'s Landing Citizen', 'Hayley McQuillan', '1', '2019', '2019'),
	('Crying Man', 'Pádraig O\'Grady', '1', '2019', '2019'),
	('Lannister Guard', 'Conor Delaney', '1', '2011', '2011'),
	('Maggy', 'Jodhi May', '1', '2015', '2015'),
	('The Waif\'s Disguise', 'Margaret Jackman', '1', '2016', '2016'),
	('Citadel Maester', 'Philip O\'Sullivan', '1', '2017', '2017'),
	('Lannister Soldier', 'Adam Devereux', '1', '2019', '2019'),
	('Lannister', 'Eoin Duffy', '1', '2019', '2019'),
	('Roslin Frey', 'Alexandra Dowling', '1', '2013', '2013'),
	('Anya Waynwood', 'Paola Dionisotti', '1', '2014', '2014'),
	('Bathhouse Prostitute', 'Samantha McEwan', '1', '2014', '2014'),
	('Braavosi Captain', 'Morgan C. Jones', '1', '2015', '2015'),
	('Ironborn #1', 'Darrell D\'Silva', '1', '2016', '2016'),
	('Westerosi Trader', 'Kevin Horsham', '1', '2016', '2016'),
	('Street Red Priestess Meereen', 'Melanie Liburd', '1', '2016', '2016'),
	('Goldcloak', 'Laurence Spellman', '1', '2017', '2017'),
	('nan', 'Conor Maguire', '1', '2019', '2019'),
	('Lannister Soldier', 'Thomas Martin', '1', '2019', '2019'),
	('Willa', 'Alice Nokes', '1', '2019', '2019'),
	('nan', 'Shane Whisker', '1', '2019', '2019'),
	('Old Man', 'Sean Buckley', '1', '2013', '2013'),
	('Yunkai\'i Whore', 'Talitha Luke-Eardley', '1', '2013', '2013'),
	('Ironborn in Skiff', 'Michael Hough', '1', '2014', '2014'),
	('Black Armored White Walker', 'Tim Loane', '1', '2015', '2015'),
	('Slaver', 'Michael Yare', '1', '2015', '2015'),
	('Bear Island Maester', 'Louis Rolston', '1', '2016', '2016'),
	('Rhaegar Targaryen', 'Wilf Scolding', '1', '2017', '2017'),
	('Fergus\' Friend', 'Thomas Finnegan', '1', '2019', '2019'),
	('Sarra', 'Danielle Galligan', '1', '2019', '2019'),
	('Lannister Soldier', 'Brian Patrick Kennedy', '1', '2019', '2019'),
	('Villager 1', 'Lorcan Strain', '1', '2019', '2019'),
	('Wine Merchant', 'Simon Lowe', '1', '2011', '2011'),
	('Frey Guard', 'A.J. Kennedy', '1', '2013', '2013'),
	('Prisoner', 'Marko Jelic', '1', '2014', '2014'),
	('Great Master #1', 'Gianpiero Cognoli', '1', '2015', '2015'),
	('Joss', 'James McKenzie Robinson', '1', '2015', '2015'),
	('Volantene Whore #1', 'Katie Alexander Thom', '1', '2016', '2016'),
	('High Septon Maynard', 'Tom Chadbon', '1', '2017', '2017'),
	('King\'s Landing Citizen', 'Luna Kalo', '1', '2019', '2019'),
	('Winterfell Girl', 'Emer McDaid', '1', '2019', '2019'),
	('nan', 'Ella-Rose Sands', '1', '2019', '2019'),
	('Pentoshi Servant', 'Rania Zouari', '1', '2011', '2011'),
	('High Septon', 'David Verrey', '1', '2012', '2012'),
	('Merry Frey', 'Grace Hendy', '1', '2013', '2013'),
	('Bolton Guard', 'Anthony Boyle', '1', '2014', '2014'),
	('Ralf Kenning', 'Grahame Fox', '1', '2014', '2014'),
	('Pit Announcer', 'Nicholas Boulton', '1', '2015', '2015'),
	('Street Red Priestess Volantis', 'Rila Fukushima', '1', '2015', '2015'),
	('Winter Town Man', 'Raymond Keane', '1', '2015', '2015'),
	('Northman Rioter', 'Jed Murray', '1', '2016', '2016'),
	('Tully Bannerman', 'Sam Redford', '1', '2016', '2016'),
	('Aerys Targaryen', 'David Rintoul', '1', '2016', '2016'),
	('Crayah', 'Lucy Aarden', '1', '2019', '2019'),
	('King\'s Landing Citizen', 'Caitlin Pharro', '1', '2019', '2019'),
	('Varly', 'Graham Charles', '1', '2011', '2011'),
	('Goldcloak', 'Alan Paris', '1', '2011', '2011'),
	('Hog Farmer', 'Pat McGrath', '1', '2013', '2013'),
	('Elder Meereen Slave', 'Philip Philmar', '1', '2014', '2014'),
	('Great Master #2', 'Bobby Asghar', '1', '2015', '2015'),
	('Wildling Rioter', 'Michael Patrick', '1', '2016', '2016'),
	('Dickon Tarly', 'Freddie Stroma', '1', '2016', '2016'),
	('Crossroads Inn Patron', 'Ben Fox', '1', '2017', '2017'),
	('Stark Soldier', 'Luke Wilson Hanley', '1', '2017', '2017'),
	('Lannister General', 'Guy Oliver-Watts', '1', '2017', '2017'),
	('Lannister Soldier', 'Ed Sheeran', '1', '2017', '2017'),
	('\'Littlefinger\' Winterfell Spy', 'Adele Smyth-Kennedy', '1', '2017', '2017'),
	('Northman', 'Robbie Beggs', '1', '2019', '2019'),
	('Dirah', 'Marina Lawrence-Mahrra', '1', '2019', '2019'),
	('King\'s Landing Citizen', 'Louis McCartney', '1', '2019', '2019'),
	('nan', 'Fionnuala Murphy', '1', '2019', '2019'),
	('White Walker #2', 'Spencer Wilding', '1', '2011', '2011'),
	('Lannister Guard', 'Sam Mackay', '1', '2012', '2012'),
	('Drowned Priest', 'Jonathan Ryan', '1', '2012', '2012'),
	('Theon\'s Master of Hounds', 'Steve Wilson', '1', '2012', '2012'),
	('Fennesz', 'Trevor Allan Davies', '1', '2014', '2014'),
	('Tansy', 'Jazzy De Lisser', '1', '2014', '2014'),
	('Goatherd\'s Son', 'Gian Sanghera-Warren', '1', '2014', '2014'),
	('Braavosi Madam', 'Lacy Moore', '1', '2015', '2015'),
	('Merchant Captain', 'Gary Pillai', '1', '2015', '2015'),
	('Great Master #3', 'Peter Silverleaf', '1', '2015', '2015'),
	('Talla Tarly', 'Rebecca Benson', '1', '2016', '2016'),
	('King\'s Landing Boaster', 'Dylan Edwards', '1', '2016', '2016'),
	('Lannister Soldier', 'Matt Faris', '1', '2016', '2016'),
	('Ash', 'Yousef \'Joe\' Sweid', '1', '2016', '2016'),
	('Crossroads Inn Patron', 'Mark Roper', '1', '2017', '2017'),
	('Lannister Soldier', 'Thomas Turgoose', '1', '2017', '2017'),
	('', 'Rosa Frazer', '1', '2019', '2019'),
	('King\'s Landing Citizen', 'Rosie McClelland', '1', '2019', '2019'),
	('nan', 'Roma Tomelty', '1', '2019', '2019'),
	('Dothraki Crone', 'Amira Ghazalla', '1', '2011', '2011'),
	('Jaremy Rykker', 'Jeffrey O\'Brien', '1', '2011', '2011'),
	('Wight Wildling Girl', 'Claire Wright', '2', '2011', '2014'),
	('Captain\'s Daughter', 'Amy Dawson', '1', '2012', '2012'),
	('Rennick', 'David Fynn', '1', '2012', '2012'),
	('Wendel Manderly', 'Oddie Braddell', '1', '2013', '2013'),
	('nan', 'Mackenzie Dean', '1', '2014', '2014'),
	('Adrack Humble', 'Jody Halse', '1', '2014', '2014'),
	('Morgan\'s Friend', 'Stuart Martin', '1', '2014', '2014'),
	('Young Braavosi', 'Jack Hickey', '1', '2015', '2015'),
	('Great Master #4', 'Davor Jozinovic', '1', '2015', '2015'),
	('Lead Dornish Guard', 'Christian Vit', '1', '2015', '2015'),
	('Moro\'s Wife #1', 'Rubi Ali', '1', '2016', '2016'),
	('Kesh', 'Michael Heath', '1', '2016', '2016'),
	('Ironborn at Brothel', 'Neil Keery', '1', '2016', '2016'),
	('Riddell', 'Ross McKinney', '1', '2016', '2016'),
	('Lannister Soldier', 'Billy Postlethwaite', '1', '2017', '2017'),
	('nan', 'Claire Connor', '1', '2019', '2019'),
	('King\'s Landing Citizen', 'Isaac Heslip', '1', '2019', '2019'),
	('Joss', 'Niall Cusack', '1', '2011', '2011'),
	('Drunk Patron', 'Paul Portelli', '1', '2011', '2011'),
	('Torrhen Karstark', 'Tyrone McElhennon', '1', '2012', '2012'),
	('Drummer', 'Will Champion', '1', '2013', '2013'),
	('Great Master #5', 'Ivan Peric', '1', '2015', '2015'),
	('Kinvara', 'Ania Bukstein', '1', '2016', '2016'),
	('Steve', 'Steve Love', '1', '2016', '2016'),
	('Volantene Whore #2', 'Heidi Romanova', '1', '2016', '2016'),
	('Tyrell Bannerman', 'Raül Tortosa', '1', '2016', '2016'),
	('Lannister Guard', 'Adam Slynn', '1', '2017', '2017'),
	('Winter Town Boy', 'Felix Jamieson', '1', '2019', '2019'),
	('Lannister Soldier', 'Jack Morgan', '1', '2019', '2019'),
	('Tomard', 'Phil Dixon', '1', '2011', '2011'),
	('Stiv', 'Stephen Don', '1', '2011', '2011'),
	('King\'s Landing Baker', 'Edward Mercieca', '1', '2011', '2011'),
	('Goldcloak #1', 'Nikovich Sammut', '1', '2011', '2011'),
	('Karstark Soldier #1', 'Neill Fleming', '1', '2012', '2012'),
	('Lordsport Dockhand', 'Jer O\'Leary', '1', '2012', '2012'),
	('Bolton Soldier', 'Bryan Quinn', '1', '2013', '2013'),
	('Leaf', 'Octavia Selena Alexandru', '1', '2014', '2014'),
	('Vance Corbray', 'Richard Doubleday', '1', '2014', '2014'),
	('Valyrian Slave', 'Robert Goodman', '1', '2014', '2014'),
	('Axell Florent', 'James McHale', '1', '2014', '2014'),
	('Innkeeper', 'Martin Walsh', '1', '2014', '2014'),
	('Great Master #6', 'Hadi Kermani', '1', '2015', '2015'),
	('Lannister Soldier', 'Brahm Gallagher', '1', '2016', '2016'),
	('Khal Forzho', 'Tamer Hassan', '1', '2016', '2016'),
	('Volantene Whore #3', 'Danielle Claire Jenner', '1', '2016', '2016'),
	('Winter Town Woman', 'Syd Ralph', '1', '2019', '2019'),
	('Goldcloak #2', 'Seamus Kelly', '1', '2011', '2011'),
	('Night\'s Watchman', 'Marcus Lamb', '1', '2011', '2011'),
	('Little Bird', 'Tristan Mercieca', '1', '2011', '2011'),
	('Knight of House Lynderly', 'Paddy Rocks', '1', '2011', '2011'),
	('Old Woman Prisoner', 'Gina Moxley', '1', '2012', '2012'),
	('Mirelle', 'Elisa Lasowski', '1', '2013', '2013'),
	('Sorcerer', 'Harold James McMullan', '1', '2013', '2013'),
	('Unsullied', 'Karl Jackson', '1', '2014', '2014'),
	('Lord Blackmont', 'Daniel Rabin', '1', '2014', '2014'),
	('Great Master #7', 'Tonci Banov', '1', '2015', '2015'),
	('Brothel Guard', 'Mishaël Lopes Cardozo', '1', '2015', '2015'),
	('Faith Militant #1', 'Simon Norbury', '1', '2015', '2015'),
	('Volantene Whore #4', 'Ella Hughes', '1', '2016', '2016'),
	('The Waif\'s Disguise', 'Adam Turns', '1', '2016', '2016'),
	('Stevron Frey', 'Colin Carnegie', '1', '2011', '2011'),
	('Eon Hunter', 'Barrington Cullen', '1', '2011', '2011'),
	('Gerald', 'Ken Fletcher', '1', '2012', '2012'),
	('Boat Commander', 'Michael Power', '1', '2013', '2013'),
	('Musician #1', 'Jon Thor Birgisson', '1', '2014', '2014'),
	('Goatherd', 'Darren Kent', '1', '2014', '2014'),
	('Kegs', 'Tim Landers', '1', '2014', '2014'),
	('Derek', 'Ian Lloyd Anderson', '1', '2015', '2015'),
	('Lollys Stokeworth', 'Elizabeth Cadwallader', '1', '2015', '2015'),
	('Despondent Man', 'David Garlick', '1', '2015', '2015'),
	('Faith Militant #2', 'Jack Olohan', '1', '2015', '2015'),
	('Volantene Whore #5', 'Zoi Gorman', '1', '2016', '2016'),
	('Winter Town Woman', 'Katie Tumelty', '1', '2019', '2019'),
	('Ryger Rivers', 'Bryan McCaugherty', '1', '2011', '2011'),
	('Night\'s Watch Deserter', 'Barry O\'Connor', '1', '2011', '2011'),
	('King\'s Landing Rioter #2', 'Marko Juraga', '1', '2012', '2012'),
	('Colen of Greenpools', 'Darren Killeen', '1', '2012', '2012'),
	('Wounded Lannister', 'Emmet O\'Riabhaigh', '1', '2012', '2012'),
	('Protestor', 'Edward Tudor-Pole', '1', '2012', '2012'),
	('Margaery\'s Handmaiden', 'Aisling Jarrett-Gavin', '1', '2013', '2013'),
	('Frey Soldier #1', 'Ciaran O\'Grady', '1', '2013', '2013'),
	('Riverlands Traveller', 'Joe Purcell', '1', '2013', '2013'),
	('Musician #2', 'Orri P. Dyrason', '1', '2014', '2014'),
	('Black Jack Bulwer', 'Cormac McDonagh', '1', '2014', '2014'),
	('Ser Endrew Tarth', 'Dez McMahon', '1', '2014', '2014'),
	('Craster\'s Wife #2', 'Aeryn Walker', '1', '2014', '2014'),
	('Brant', 'Jonathan Byrne', '1', '2015', '2015'),
	('Faceless Man', 'Cedric Henderson', '1', '2015', '2015'),
	('Sellsword #1', 'Matt McArdle', '1', '2015', '2015'),
	('Second Son', 'Slavko Sobin', '1', '2015', '2015'),
	('Rickard Stark', 'Wayne Foskett', '1', '2016', '2016'),
	('Ironborn Abusing a Volantene Whore', 'Billy King', '1', '2016', '2016'),
	('Poisoned Frey', 'Paul Ward', '1', '2017', '2017'),
	('King\'s Landing Urchin', 'Stephen Grech', '1', '2011', '2011'),
	('Beric Dondarrion', 'David Michael Scott', '1', '2011', '2011'),
	('Tortured Prisoner', 'Donal Gallery', '1', '2012', '2012'),
	('Karstark Soldier #2', 'Duncan Lacroix', '1', '2012', '2012'),
	('King\'s Landing Rioter #3', 'Rea Separovic', '1', '2012', '2012'),
	('Orphan Kid', 'Max Barber', '1', '2013', '2013'),
	('Karstark Lookout', 'Shaun Blaney', '1', '2013', '2013'),
	('King\'s Landing Tailor', 'Joe Cassidy', '1', '2013', '2013'),
	('Frey Soldier #2', 'Michael Liebmann', '1', '2013', '2013'),
	('Musician #3', 'Georg Holm', '1', '2014', '2014'),
	('Craster\'s Wife #3', 'Cheryl Lester', '1', '2014', '2014'),
	('Farmer Hamlet', 'Finbar Lynch', '1', '2014', '2014'),
	('Mully', 'Andy Moore', '1', '2014', '2014'),
	('Tyrell Guard', 'Nikola Bace', '1', '2015', '2015'),
	('Sellsword #2', 'Eddie Elks', '1', '2015', '2015'),
	('Lannister Guard #1', 'Danny O\'Connor', '1', '2015', '2015'),
	('Lead Kingsguard', 'Paddy Wallace', '1', '2015', '2015'),
	('Arthur Dayne', 'Luke Roberts', '1', '2016', '2016'),
	('Frey Lord', 'Brendan Morrissey', '1', '2017', '2017'),
	('Reginald Lannister', 'Patrick FitzSymons', '1', '2012', '2012'),
	('Brothel Customer', 'Derek Reid', '1', '2012', '2012'),
	('Violet', 'Stephanie Blacker', '1', '2013', '2013'),
	('Fruit Vendor', 'Alex Mileman', '1', '2013', '2013'),
	('Tyrell Servant', 'Will Rastall', '1', '2013', '2013'),
	('Warlock', 'Lottie Steer', '1', '2013', '2013'),
	('King Joffrey Baratheon Dwarf', 'Raymond Griffiths', '1', '2014', '2014'),
	('Wight', 'Alice Hewkin', '1', '2014', '2014'),
	('Little Bird', 'Samuel Paul Small', '1', '2014', '2014'),
	('Clea', 'Gwyneth Keyworth', '1', '2015', '2015'),
	('Brusco', 'Garry Mountaine', '1', '2015', '2015'),
	('Foreign Merchant', 'Allon Sylvain', '1', '2015', '2015'),
	('Gerold Hightower', 'Eddie Eyre', '1', '2016', '2016'),
	('Lannister Captain', 'Richard Laing', '1', '2016', '2016'),
	('Iggo', 'Deon Lee-Williams', '1', '2016', '2016'),
	('Sick Maester', 'Eamonn Draper', '1', '2017', '2017'),
	('Rickard Karstark', 'Steve Blount', '1', '2011', '2011'),
	('Unsullied', 'Rhys Howells', '1', '2013', '2013'),
	('nan', 'Jon Freeman', '1', '2014', '2014'),
	('Whore #1', 'Kristen Gillespie', '1', '2014', '2014'),
	('King Stannis Baratheon Dwarf', 'Maxwell Laird', '1', '2014', '2014'),
	('Sailor', 'Dylan McDonough', '1', '2015', '2015'),
	('Beggar Woman', 'Emina Muftic', '1', '2015', '2015'),
	('Denys Mallister', 'J.J. Murphy', '1', '2015', '2015'),
	('Young Cersei Lannister', 'Nell Williams', '1', '2015', '2015'),
	('Khal Brozho', 'Elie Haddad', '1', '2016', '2016'),
	('Jonos Bracken', 'Gerry O\'Brien', '1', '2011', '2011'),
	('Stark Messenger', 'Moe Dunford', '1', '2012', '2012'),
	('Jaqen\'s Disguise', 'Patrick O\'Kane', '1', '2012', '2012'),
	('Desmond Crakehall', 'Maro Drobnic', '1', '2013', '2013'),
	('Guymon', 'Jem Wall', '1', '2014', '2014'),
	('King Renly Baratheon Dwarf', 'Dean Whatton', '1', '2014', '2014'),
	('nan', 'Rob Brockman', '1', '2015', '2015'),
	('Baratheon General', 'Nigel O\'Neill', '1', '2015', '2015'),
	('Melara Hetherspoon', 'Isabella Steinbarth', '1', '2015', '2015'),
	('Braavosi Woman #1', 'Kate Anthony', '1', '2016', '2016'),
	('Khal Rhalko', 'Andrei Claude', '1', '2016', '2016'),
	('Young Lyanna Stark', 'Cordelia Hill', '1', '2016', '2016'),
	('Knight of House Frey', 'Patrick Ryan', '1', '2011', '2011'),
	('Lannister Messenger', 'Simon Stewart', '1', '2011', '2011'),
	('Lannister Torturer', 'Mark Byatt', '1', '2012', '2012'),
	('Northern Lord', 'Pat Mooney', '1', '2012', '2012'),
	('Stark Soldier', 'Michael Shaeffer', '1', '2012', '2012'),
	('Yunkai\'i Slave #1', 'Marin Tudor', '1', '2013', '2013'),
	('King Robb Stark Dwarf', 'George Appleby', '1', '2014', '2014'),
	('Innkeeper\'s Daughter', 'Gabrielle Dempsey', '1', '2014', '2014'),
	('Olly\'s Mother', 'Raewyn Lippert', '1', '2014', '2014'),
	('Street Tough #1', 'Tom Fava', '1', '2015', '2015'),
	('Septa Moelle', 'Maggie Hayes', '1', '2015', '2015'),
	('White Rat', 'Marcos James', '1', '2015', '2015'),
	('nan', 'Daniel Johnson', '1', '2015', '2015'),
	('Anara', 'Ollie Kram', '1', '2015', '2015'),
	('Citadel Maester', 'Frank Hvam', '1', '2016', '2016'),
	('Khal Qorro', 'Darius Dar Khan', '1', '2016', '2016'),
	('Braavosi Woman #2', 'Sally Mortemore', '1', '2016', '2016'),
	('Serving Girl', 'Kate Dempsey', '1', '2017', '2017'),
	('Addam Marbrand', 'B.J. Hogg', '1', '2011', '2011'),
	('Vayon Poole', 'Matthew Scurfield', '1', '2011', '2011'),
	('Yunkai\'i Slave #2', 'Roxana Kadyrova', '1', '2013', '2013'),
	('Bolton Soldier', 'Gary Lightbody', '1', '2013', '2013'),
	('King Balon Greyjoy Dwarf', 'Krysten Coombs', '1', '2014', '2014'),
	('Whore #2', 'Maria Sikavica', '1', '2014', '2014'),
	('nan', 'Richard Fitzwell', '1', '2015', '2015'),
	('Strong Sam Stone', 'Allan Gildea', '1', '2015', '2015'),
	('Septa Scolera', 'Mary Jordan', '1', '2015', '2015'),
	('Mallister Supporter', 'Derek Lord', '1', '2015', '2015'),
	('Brea', 'Gemita Samarra', '1', '2015', '2015'),
	('Masha Heddle', 'Susie Kelly', '1', '2011', '2011'),
	('Stark Guard', 'Faolan Morgan', '1', '2011', '2011'),
	('Night\'s Watch Messenger', 'Frank O\'Sullivan', '1', '2011', '2011'),
	('Septon', 'Terry Byrne', '1', '2012', '2012'),
	('Qartheen Woman', 'Kristina Krepela', '1', '2012', '2012'),
	('Craster\'s Wife', 'Michelle Costello', '1', '2013', '2013'),
	('Yunkai\'i Slave #3', 'Jamal Ouarraq', '1', '2013', '2013'),
	('Eyrie Guard', 'Paul Kennedy', '1', '2015', '2015'),
	('Whore', 'Irma Mali', '1', '2015', '2015'),
	('Brothel Customer', 'Ben Yates', '1', '2015', '2015'),
	('Night\'s Watchman #2', 'Ruairí Heading', '1', '2016', '2016'),
	('Lannister Soldier', 'Ciaran McMahon', '1', '2012', '2012'),
	('Yunkai\'i Slave #4', 'El Hasani', '1', '2013', '2013'),
	('Craster\'s Younger Wife', 'Lisa Walsh', '1', '2013', '2013'),
	('Sparring Boy', 'Stephen Brown', '1', '2015', '2015'),
	('Street Tough #2', 'Winston Davis', '1', '2015', '2015'),
	('Aya', 'Aifric O\'Donnell', '1', '2015', '2015'),
	('Brothel Child #1', 'Ella Tweed', '1', '2015', '2015'),
	('Bolton Officer', 'Andrew Bryan', '1', '2016', '2016'),
	('Lannister Scout', 'Chris Gallagher', '1', '2011', '2011'),
	('Rhaego', 'Wren Ros Elliot-Sloan', '1', '2012', '2012'),
	('Yunkai\'i Slave #5', 'Mustapha Mekanassi', '1', '2013', '2013'),
	('Maester Helliweg', 'Joe Hewetson', '1', '2015', '2015'),
	('Brothel Child #2', 'Isabelle Jones', '1', '2015', '2015'),
	('Inn Waitress', 'Irene Kelleher', '1', '2015', '2015'),
	('Lannister Guard #2', 'Fiach Kunz', '1', '2015', '2015'),
	('Handmaid', 'Sabrina Bartlett', '1', '2016', '2016'),
	('Bolton Soldier', 'Tristan Heanue', '1', '2016', '2016'),
	('Ironborn #3', 'James Lecky', '1', '2016', '2016'),
	('Stark Guard', 'Rick Burn', '1', '2011', '2011'),
	('Genna', 'Kylie Harris', '1', '2013', '2013'),
	('Son of the Harpy', 'Curtis-Lee Ashqar', '1', '2015', '2015'),
	('Baratheon Soldier #1', 'David Fennelly', '1', '2015', '2015'),
	('Lannister Guard #3', 'Michael Johnston', '1', '2015', '2015'),
	('Meereenese Homeless Mother', 'Sabina Arthur', '1', '2016', '2016'),
	('Tommen\'s Attendant', 'Dermot Ward', '1', '2016', '2016'),
	('Red Keep Stableboy', 'Hugo Culverhouse', '1', '2011', '2011'),
	('Night\'s Watchman', 'Patrick J Molloy', '1', '2014', '2014'),
	('Dwarf Hunter #1', 'Jonathan Gunning', '1', '2015', '2015'),
	('Maester Caleotte', 'Colin Azzopardi', '1', '2016', '2016'),
	('Tommen\'s Manservant', 'Aron Hegarty', '1', '2016', '2016'),
	('Chella', 'Natalia Lee', '1', '2012', '2012'),
	('Gordy', 'Tristan McConnell', '1', '2015', '2015'),
	('Dwarf Hunter #2', 'Alan McKee', '1', '2015', '2015'),
	('Wyman Manderly', 'Sean Blowers', '1', '2016', '2016'),
	('Lord Portan', 'Gordon Fulton', '1', '2012', '2012'),
	('Farmer\'s Daughter', 'Trixiebell Harrowell', '1', '2014', '2014'),
	('Simpson', 'Laurence O\'Fuarain', '1', '2015', '2015'),
	('Cley Cerwyn', 'Tom Varey', '1', '2016', '2016'),
	('Tourney Herald', 'Marko Cindric', '1', '2012', '2012'),
	('Tortured Slave', 'Mark Drake', '1', '2013', '2013'),
	('Woodcutter', 'Ralph Clemente', '1', '2015', '2015'),
	('Dothraki Man Having Sex', 'Oliver Stockwell', '1', '2016', '2016'),
	('King\'s Landing Drunkard', 'Anthony John Crocker', '1', '2015', '2015'),
	('Great Master #2', 'Derek Horsham', '1', '2014', '2014'),
	('King\'s Landing Whore', 'Kirsty Nicholls', '1', '2015', '2015'),
	('Meereen Slave', 'Joshua Sher', '1', '2014', '2014'),
	('King\'s Landing Flasher #1', 'Munro Graham', '1', '2015', '2015'),
	('King\'s Landing Flasher #2', 'Ben Kelly', '1', '2015', '2015'),
	('Cersei Body Double', 'Rebecca Van Cleave', '1', '2015', '2015'),
	('The Bear', 'Bart the Bear', '1', '2013', '2013'),
	('Night\'s Watch Officer', 'Michael Stuart', '19', '2013', '2019'),
	('Baratheon Soldier', 'Graeme Peacock', '11', '2012', '2017'),
	('Baratheon Soldier', 'Mark Quigley', '11', '2014', '2019'),
	('Stark Soldier', 'Andrew McClay', '10', '2015', '2019'),
	('Night\'s Watch', 'Bobby Marno', '10', '2015', '2017'),
	('Baratheon Soldier', 'James Bleakney', '9', '2013', '2016'),
	('Ironborn', 'Logan Bruce', '6', '2013', '2019'),
	('Brotherhood Member', 'Tyrone Kearns', '6', '2013', '2016'),
	('Knight of the Vale', 'Micheal Fitzgerald', '6', '2016', '2019'),
	('Unsullied', 'Stephen Presley', '6', '2019', '2019'),
	('Unsullied', 'Andrew Watson', '6', '2019', '2019'),
	('Northern Lord', 'Robert Brown', '5', '2015', '2019'),
	('Knight', 'Frédéric André', '4', '2011', '2016'),
	('Craster\'s Wife', 'Kristy Robinson', '4', '2012', '2015'),
	('Wildling', 'Jessica Odell', '4', '2015', '2016'),
	('Stark Archer', 'Patrick Kelly', '4', '2016', '2019'),
	('King\'s Landing Nobleman', 'Frank Cannon', '3', '2015', '2016'),
	('Dothraki woman', 'Mariola Sanz', '3', '2015', '2016'),
	('Meereen Guard', 'Juan Carlos Martínez Antuña', '3', '2017', '2017'),
	('Unsullied Soldier', 'Jaryd Headley', '3', '2019', '2019'),
	('Wildling', 'Brian Kearns', '3', '2019', '2019'),
	('Lord Galbart Glover', 'Mark Coney', '2', '2011', '2011'),
	('Mikken', 'Boyd Rankin', '2', '2011', '2011'),
	('Nobleman', 'Aaron Archer', '2', '2012', '2016'),
	('Frey Wedding Guest', 'Darragh O\'Connor', '2', '2013', '2016'),
	('Frey Wedding Guest', 'Laurence Doherty', '2', '2013', '2014'),
	('Night\'s Watch', 'Gerald McMullan', '2', '2014', '2017'),
	('Dothraki Rider', 'Daniel Naprous', '2', '2014', '2017'),
	('King\'s Landing Handmaiden', 'Niamh Lennon', '2', '2014', '2014'),
	('Mole\'s Town Whore', 'Marion McDowell', '2', '2014', '2014'),
	('Tyrell Cousin', 'Kylie Zimmer', '2', '2014', '2014'),
	('Burning Lannister', 'Calvin Warrington-Heasman', '2', '2015', '2017'),
	('Tully Soldier', 'Simon Millar', '2', '2015', '2016'),
	('Wildling', 'Jessica Stevenson', '2', '2015', '2015'),
	('Karstark Soldier', 'Peter Rooney', '2', '2016', '2019'),
	('Bolton Infantry', 'Kevin-Barry Brown', '2', '2016', '2016'),
	('Kingsland Taverner', 'Michael William Burns', '2', '2016', '2016'),
	('Braavosi Theatre Server', 'Tamsin Greene Barker', '2', '2016', '2016'),
	('Braavosi Theatre Sound Artist', 'Kiran Shah', '2', '2016', '2016'),
	('Meereen Guard', 'Hugh Yeaman', '2', '2016', '2016'),
	('Captured Wight', 'Michael Byrch', '2', '2017', '2017'),
	('Lady of Winterfell', 'Canan Avsar', '2', '2019', '2019'),
	('Dothraki Rider', 'Spencer Collings', '2', '2019', '2019'),
	('Baratheon Guard', 'Phil Barnhill', '1', '2011', '2011'),
	('Prostitute', 'Caroline Davis', '1', '2011', '2011'),
	('Winterfell Beekeeper', 'Owen Dickey', '1', '2011', '2011'),
	('Mago', 'Ivailo Dimitrov', '1', '2011', '2011'),
	('Lady of Eyrie Landing (2011)', 'Bernadette Dobbin', '1', '2011', '2011'),
	('Peasant', 'Melissa Reid', '1', '2011', '2011'),
	('Lannister Guard', 'James Tolcher', '1', '2011', '2011'),
	('King\'s Guard', 'Robert Yates', '1', '2011', '2011'),
	('Baratheon Archer', 'Robert Atkinson', '1', '2012', '2012'),
	('Wight', 'Noel Cecil', '1', '2012', '2012'),
	('Black Knight', 'Jonathan Cohen', '1', '2012', '2012'),
	('Lannister Archer', 'Hugh Irvine', '1', '2012', '2012'),
	('Weasel', 'Paul Kealyn', '1', '2012', '2012'),
	('Selyse Baratheon', 'Sarah Mac Keever', '1', '2012', '2012'),
	('Young Nobleman', 'Filip Lozic', '1', '2012', '2012'),
	('Stark Guard', 'Paul Monahan', '1', '2012', '2012'),
	('Craster\'s Daughter', 'Ginger A. Taylor', '1', '2012', '2012'),
	('Riverrun Nobleman', 'Matt Butcher', '1', '2013', '2013'),
	('Marianne Frey', 'Katie Creaven', '1', '2013', '2013'),
	('Musician', 'Kevin McCann', '1', '2013', '2013'),
	('Hoster Tully', 'Christopher Newman', '1', '2013', '2013'),
	('Bathhouse Boy', 'Niall O\'Donnell', '1', '2013', '2013'),
	('Khaleesi Handmaiden #1', 'Rachel Puchkoff', '1', '2013', '2013'),
	('Yunkai Citizen', 'Mustapha Rachidi', '1', '2013', '2013'),
	('Dothraki', 'Omar Youssef', '1', '2013', '2013'),
	('Noble Man', 'Neil Baltus', '1', '2014', '2014'),
	('Waitress', 'Emma Bryant', '1', '2014', '2014'),
	('Cooper', 'Joe Claflin', '1', '2014', '2014'),
	('Dragonstone waiter', 'Bryan Cogman', '1', '2014', '2014'),
	('Stannis Guard', 'Oisin De Lange', '1', '2014', '2014'),
	('Wedding Guest', 'Paul Herbert', '1', '2014', '2014'),
	('Inn Customer', 'Phelim Kelly', '1', '2014', '2014'),
	('Frey Serving Boy', 'Mark Kelvin Ryan', '1', '2014', '2014'),
	('Noble Lady', 'Stella Lutz', '1', '2014', '2014'),
	('Night\'s Watch Archer', 'Neil Marshall', '1', '2014', '2014'),
	('Donnel Hill', 'Jack Roth', '1', '2014', '2014'),
	('Wedding Band', 'Sigur Rós', '1', '2014', '2014'),
	('Wedding Guest', 'C.C. Smiff', '1', '2014', '2014'),
	('Strong Fighter', 'Adam Basil', '1', '2015', '2015'),
	('Fighter', 'Roman Beguns', '1', '2015', '2015'),
	('Wildling', 'Brann Dailor', '1', '2015', '2015'),
	('Fighter', 'Rob de Groot', '1', '2015', '2015'),
	('Wildling Archer', 'Jenny Edgar', '1', '2015', '2015'),
	('Wight', 'Cassie Friel', '1', '2015', '2015'),
	('Wildling', 'Brent Hinds', '1', '2015', '2015'),
	('Slave', 'Terence Hughes', '1', '2015', '2015'),
	('Pit Fighter', 'Charles Jarman', '1', '2015', '2015'),
	('Wilding Gladiator', 'Danko Jordanov', '1', '2015', '2015'),
	('Wildling', 'Bill Kelliher', '1', '2015', '2015'),
	('Night\'s Watch Recruit', 'Christopher Kinkead', '1', '2015', '2015'),
	('Wildling Archer', 'Chelsea Mainwaring', '1', '2015', '2015'),
	('Wight', 'Barrie Martin', '1', '2015', '2015'),
	('Wildling', 'Elaine O\'Dwyer', '1', '2015', '2015'),
	('Wildling', 'Royd Tolkien', '1', '2015', '2015'),
	('Passerby', 'Kerim Topcic', '1', '2015', '2015'),
	('Unsullied Guard', 'Pablo Verdejo', '1', '2015', '2015'),
	('Volantene Whore', 'Raquel Arraes', '1', '2016', '2016'),
	('Child of the Forest #1', 'Kristina Baskett', '1', '2016', '2016'),
	('Child of the Forest #2', 'Rachelle Beinart', '1', '2016', '2016'),
	('Tavern Maid', 'Elynia Betts', '1', '2016', '2016'),
	('Volantene Whore', 'Susan Christie', '1', '2016', '2016'),
	('Frey Daughter', 'Milly Burke Cunningham', '1', '2016', '2016'),
	('Quinn', 'Oryan Landa', '1', '2016', '2016'),
	('\'That\'s Right\' Man', 'Jose Mellinas', '1', '2016', '2016'),
	('Child of the Forest #3', 'Casey Michaels', '1', '2016', '2016'),
	('Volantene Whore', 'Sophia Smith', '1', '2016', '2016'),
	('Healtor Troop', 'Gary Wales', '1', '2016', '2016'),
	('Howland Reed', 'Leo Woodruff', '1', '2016', '2016'),
	('Dothraki Rider', 'Charlie Barrett', '1', '2017', '2017'),
	('Traveller', 'Dario Cannizzaro', '1', '2017', '2017'),
	('Woman in King\'s Landing', 'Carolina Castellano', '1', '2017', '2017'),
	('Wildling', 'Dan Euston', '1', '2017', '2017'),
	('Lannister Guard', 'Christian Gimse', '1', '2017', '2017'),
	('Lannister Soldier', 'Seán McGillicuddy', '1', '2017', '2017'),
	('Night\'s Watch', 'Brendan McGivern', '1', '2017', '2017'),
	('Tyrell Guard', 'Ross Moneypenny', '1', '2017', '2017'),
	('Burning Lannister', 'Douglas Robson', '1', '2017', '2017'),
	('Lannister Map Painter', 'Jim Stanes', '1', '2017', '2017'),
	('Lannister Spearman', 'Noah Syndergaard', '1', '2017', '2017'),
	('Unsullied', 'Louis Agbodo', '1', '2019', '2019'),
	('King\'s Landing Citizen', 'Lorenzo Antonucci', '1', '2019', '2019'),
	('Wildling #2', 'David Benioff', '1', '2019', '2019'),
	('Lannister Archer', 'Brian Black', '1', '2019', '2019'),
	('Alanna', 'Kim Chapman', '1', '2019', '2019'),
	('Soldier', 'Sophie Ellis-Bextor', '1', '2019', '2019'),
	('Ironborn #3', 'Dave Hill', '1', '2019', '2019'),
	('Wight', 'Jack Hudson', '1', '2019', '2019'),
	('Soldier', 'Richard Jones', '1', '2019', '2019'),
	('Ironborn #1', 'Rob McElhenney', '1', '2019', '2019'),
	('King\'s Landing Citizen', 'Patrick McGilligan', '1', '2019', '2019'),
	('Stark Guard', 'Jesse Morris', '1', '2019', '2019'),
	('Lannister Officer', 'Duncan Muggoch', '1', '2019', '2019'),
	('Grieving Daughter', 'Michelle O\'Flaherty', '1', '2019', '2019'),
	('Lannister Guard', 'Adam Quigley-Nixon', '1', '2019', '2019'),
	('King\'s Landing Citizen', 'Aaron Rodgers', '1', '2019', '2019'),
	('Old Man', 'Derek Smith', '1', '2019', '2019'),
	('Wildling Wight', 'Chris Stapleton', '1', '2019', '2019'),
	('Ironborn #2', 'Martin Starr', '1', '2019', '2019'),
	('Soldier', 'Vasco Temudo', '1', '2019', '2019'),
	('Wildling #1', 'D.B. Weiss', '1', '2019', '2019'),
	('Wight', 'Gareth Wright', '1', '2019', '2019');